// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Service.Database;

#nullable disable

namespace Service.Database.Migrations
{
    [DbContext(typeof(AssessmentContext))]
    [Migration("20220531072300_ReleaseSeed")]
    partial class ReleaseSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Model.Assessment", b =>
                {
                    b.Property<int>("AssessmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssessmentId"), 1L, 1);

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("AssessmentId");

                    b.HasIndex("GroupId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Assessments");
                });

            modelBuilder.Entity("Model.Competence", b =>
                {
                    b.Property<int>("CompetenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompetenceId"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FormId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("CompetenceId");

                    b.HasIndex("FormId");

                    b.ToTable("Competences");

                    b.HasData(
                        new
                        {
                            CompetenceId = 1,
                            Evidence = "Product Backlog\r\nSprint Backlog\r\nBeschreven Business Case (eventueel als inleiding bij het functioneel ontwerp)\r\nAnder bewijsmateriaal zoals: interviewverslagen, schetsen van UML-diagrammen, foto’s van schetsen op whiteboards\r\nPortfolio: Reflectie op competentie Analyse & Onderzoek",
                            FormId = 1,
                            Name = "Analyseren",
                            Weight = 0.10000000000000001
                        },
                        new
                        {
                            CompetenceId = 2,
                            Evidence = "Sprint review\r\nSprint planning\r\nProduct backlog\r\nSprint backlog\r\nDefinition of Done\r\nPortfolio: Reflectie op competentie Advies en Communicatie",
                            FormId = 1,
                            Name = "Adviseren",
                            Weight = 0.10000000000000001
                        },
                        new
                        {
                            CompetenceId = 3,
                            Evidence = "Het functioneel ontwerp - Usecase/Userstory diagram, Domeinmodel en evt. andere diagrammen\r\nHet technisch ontwerp  – ERD, (UML-)diagrammen\r\nTestscenario’s (evt. in het functioneel ontwerp)\r\nPortfolio: Reflectie op competentie Ontwerp en Architectuur",
                            FormId = 1,
                            Name = "Ontwerpen",
                            Weight = 0.20000000000000001
                        },
                        new
                        {
                            CompetenceId = 4,
                            Evidence = "Broncode\r\nTestscenario’s (evt. in het functioneel ontwerp)\r\nTestprocedure\r\nTestrapportages\r\nTestprocedure\r\nUnit testen\r\nCode conventies\r\nInstallatiehandleiding\r\nPortfolio: Reflectie op competentie Realisatie en Testen ",
                            FormId = 1,
                            Name = "Realiseren",
                            Weight = 0.29999999999999999
                        },
                        new
                        {
                            CompetenceId = 5,
                            Evidence = "Dagelijkse Scrum\r\nSprint review\r\nRetrospective \r\nProduct backlog\r\nSprint backlog\r\nBurn down charts\r\nPortfolio: reflective op competentie management en beheer ",
                            FormId = 1,
                            Name = "Beheren",
                            Weight = 0.20000000000000001
                        },
                        new
                        {
                            CompetenceId = 6,
                            Evidence = "Retrospective\r\nPortfolio: Hoofdstuk 'Professionele ontwikkeling'",
                            FormId = 1,
                            Name = "Professionele Ontwikkeling",
                            Weight = 0.10000000000000001
                        });
                });

            modelBuilder.Entity("Model.Criterion", b =>
                {
                    b.Property<int>("CriterionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CriterionId"), 1L, 1);

                    b.Property<int>("CompetenceId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CriterionId");

                    b.HasIndex("CompetenceId");

                    b.ToTable("Criteria");

                    b.HasData(
                        new
                        {
                            CriterionId = 1,
                            CompetenceId = 1,
                            Description = "Alle gerealiseerde sprint backlog items zijn terug te vinden in het functioneel ontwerp. Denk onder andere aan een bijgewerkt domeinmodel  en use case diagram. De uitgewerkte backlog items zijn in het functioneel ontwerp terug te vinden als uitgewerkte user-stories. Waar zinvol is het functioneel ontwerp ondersteunt met activiteitendiagrammen, toestandsdiagrammen en sequentiediagrammen.",
                            Name = "Methodische requirement analyse"
                        },
                        new
                        {
                            CriterionId = 2,
                            CompetenceId = 1,
                            Description = "De business case (de rechtvaardiging van het project, de probleemstelling, de opdracht) is beschreven en afgestemd met de opdrachtgever.",
                            Name = "Afgestemde BC"
                        },
                        new
                        {
                            CriterionId = 3,
                            CompetenceId = 1,
                            Description = "De productbacklog wordt continue aangevuld met items die tijdens de analyse (bijvoorbeeld tijdens sprint planning meetings) van het op te lossen ‘probleem’, naar voren komen.",
                            Name = "Continu aangevulde PBL"
                        },
                        new
                        {
                            CriterionId = 4,
                            CompetenceId = 1,
                            Description = "Sprintbacklog items zijn tot in voldoende detail geanalyseerd en systematisch uitgewerkt. (Voldoende detail = Gemaakte keuzes worden door alle belanghebbenden begrepen). Hulpmiddelen daarbij zijn o.a.: Userstories incl. scherm/interactie/navigatie-ontwerp, Domeinmodel, Usecase/Userstory diagram.",
                            Name = "Gedetailleerde BLI"
                        },
                        new
                        {
                            CriterionId = 5,
                            CompetenceId = 2,
                            Description = "De product owner is gedurende alle sprints tijdig en volledig geinformeerd.",
                            Name = "Geïnformeerde PO"
                        },
                        new
                        {
                            CriterionId = 6,
                            CompetenceId = 2,
                            Description = "Er zijn geschikte communicatievormen gekozen en daadwerkelijk toegepast met als doel adviezen te geven.",
                            Name = "Communicatievormen"
                        },
                        new
                        {
                            CriterionId = 7,
                            CompetenceId = 2,
                            Description = "Alle documenten zijn geschreven in correct Nederlands, zijn helder en duidelijk. ",
                            Name = "Correct Nederlands"
                        },
                        new
                        {
                            CriterionId = 8,
                            CompetenceId = 2,
                            Description = "Het scrum team denkt mee met de product owner (denk aan sprint planning). Het scrum team komt bijvoorbeeld met alternatieven voor wensen van de productowner die minder tijd kosten om te implementeren.",
                            Name = "Meedenken met PO"
                        },
                        new
                        {
                            CriterionId = 9,
                            CompetenceId = 3,
                            Description = "Alle gerealiseerde sprint backlog items zijn terug te vinden in het functioneel ontwerp. Denk onder andere aan een bijgewerkt domeinmodel en use case diagram. De uitgewerkte backlog items zijn in het functioneel ontwerp terug te vinden als uitgewerkte user-stories. Waar zinvol is het functioneel ontwerp ondersteunt met activiteitendiagrammen, toestandsdiagrammen en sequentiediagrammen.",
                            Name = "BLI in FO"
                        },
                        new
                        {
                            CriterionId = 10,
                            CompetenceId = 3,
                            Description = "Tijdens elke sprint wordt het ontwerp bijgewerkt. Denk bijvoorbeeld aan het toevoegen en/of uitbreiden van klassen in de verschillende klassendiagrammen. Belangrijke technische aspecten worden uitgelegd en ondersteund door (UML-)diagrammen.",
                            Name = "Bijwerken van ontwerp"
                        },
                        new
                        {
                            CriterionId = 11,
                            CompetenceId = 3,
                            Description = "Het functioneel ontwerp en het technisch ontwerp zijn volledig consistent met elkaar.",
                            Name = "Consistent FO en TO"
                        },
                        new
                        {
                            CriterionId = 12,
                            CompetenceId = 3,
                            Description = "Tijdens elke sprint wordt het ERD bijgewerkt (indien van toepassing). Keuzes voor het db-ontwerp (bijv. een extra index) worden toegelicht. De naamgeving van de tabellen en kollomen van de database zijn consistent met de naamgeving zoals gebruikt in het domeinmodel",
                            Name = "Bijgewerkt ERD"
                        },
                        new
                        {
                            CriterionId = 13,
                            CompetenceId = 3,
                            Description = "De gevolgde architectuur en ontwerpkeuzes zijn in het technisch ontwerp toegelicht en gemotiveerd.",
                            Name = "Toegelicht TO"
                        },
                        new
                        {
                            CriterionId = 14,
                            CompetenceId = 3,
                            Description = "In het ontwerp is alle benodige informatie opgenomen om een nieuw teamlid snel op weg te helpen met het realiseren van de software. Naast de eerder genoemde aspecten kun je daarbij ook denken aan het vermelden van gebruikte tools, frameworks en verwijzingingen naar bruikbaar studiemateriaal.",
                            Name = "Zelfstandig ontwerp"
                        },
                        new
                        {
                            CriterionId = 15,
                            CompetenceId = 3,
                            Description = "Voor ieder gerealiseerd item is een uitgebreide testset beschreven, waarmee de kwaliteit van de gerealiseerde software aangetoond kan worden.",
                            Name = "Testset voor ieder BLI"
                        },
                        new
                        {
                            CriterionId = 16,
                            CompetenceId = 4,
                            Description = "Alle broncode is op consistente wijze van commentaar voorzien.",
                            Name = "Comments"
                        },
                        new
                        {
                            CriterionId = 17,
                            CompetenceId = 4,
                            Description = "Code coventies zijn beschreven en nageleefd.",
                            Name = "Coding conventions"
                        },
                        new
                        {
                            CriterionId = 18,
                            CompetenceId = 4,
                            Description = "De code is consistent  met het opgestelde ontwerp.",
                            Name = "Consistentie"
                        },
                        new
                        {
                            CriterionId = 19,
                            CompetenceId = 4,
                            Description = "Er is een testprocedure beschreven waarin o.a. vastligt wie, wat en wanneer test.",
                            Name = "Testprocedure"
                        },
                        new
                        {
                            CriterionId = 20,
                            CompetenceId = 4,
                            Description = "De student rapporteert over unit-testen en overige testen.",
                            Name = "Testrapportage"
                        },
                        new
                        {
                            CriterionId = 21,
                            CompetenceId = 4,
                            Description = "Waar zinvol, zijn unit-testen toegepast.",
                            Name = "Unit tests"
                        },
                        new
                        {
                            CriterionId = 22,
                            CompetenceId = 4,
                            Description = "Alle namen in de code gebruiken een consistente vocabulair. Namen in de code beschrijven de intentie van de code.",
                            Name = "Self-documenting code"
                        },
                        new
                        {
                            CriterionId = 23,
                            CompetenceId = 4,
                            Description = "Formattering geeft een perfect inzicht in de beoogde structuur.",
                            Name = "Formatting"
                        },
                        new
                        {
                            CriterionId = 24,
                            CompetenceId = 4,
                            Description = "De code in methodes is voor de gewenste functionaliteit eenvoudig van opzet.",
                            Name = "Refactoring"
                        },
                        new
                        {
                            CriterionId = 25,
                            CompetenceId = 4,
                            Description = "De code is modulair opgezet en daardoor makkelijk te onderhouden, te lezen en te unit testen.",
                            Name = "Scalability"
                        },
                        new
                        {
                            CriterionId = 26,
                            CompetenceId = 5,
                            Description = "Tijdens elke Sprint Review wordt duidelijk aangegeven welke items in de sprint opgenomen zijn en welke items daarvan wel dan wel niet zijn gerealiseerd. Per gerealiseerd item wordt een demo gegeven.",
                            Name = "Opgenomen items in SR"
                        },
                        new
                        {
                            CriterionId = 27,
                            CompetenceId = 5,
                            Description = "Tijdens elke Sprint Review wordt de burn down chart besproken. Wat was de geplande velocity en waar is het team op uitgekomen?",
                            Name = "Besproken BDC in SR"
                        },
                        new
                        {
                            CriterionId = 28,
                            CompetenceId = 5,
                            Description = "Scrum stand-ups worden dagelijks en getimeboxed (bijv. max 15 minuten) uitgevoerd en zijn navolgbaar (foto’s, reflectie) voor de assessoren.",
                            Name = "Daily standup"
                        },
                        new
                        {
                            CriterionId = 29,
                            CompetenceId = 5,
                            Description = "Er is een geschikte tool en systematiek geselecteerd voor het managen van de product backlog items. Dit wordt in het reflectieverslag besproken.",
                            Name = "Tool voor BLI"
                        },
                        new
                        {
                            CriterionId = 30,
                            CompetenceId = 5,
                            Description = "Er is een geschikte tool en systematiek geselecteerd voor het samenwerken aan en het beheren van de broncode. Dit wordt in het reflectieverslag besproken.",
                            Name = "Version control system"
                        },
                        new
                        {
                            CriterionId = 31,
                            CompetenceId = 5,
                            Description = "Productbacklog items zijn in voldoende detail en consistent beschreven in de product backlog..",
                            Name = "Gedetaileerde BLI"
                        },
                        new
                        {
                            CriterionId = 32,
                            CompetenceId = 5,
                            Description = "Productbacklog items met een hoge prioriteit zijn al duidelijk verder uitgewerkt in vergelijking met items met een lage prioriteit.",
                            Name = "Geprioriteerde BLI"
                        },
                        new
                        {
                            CriterionId = 33,
                            CompetenceId = 5,
                            Description = "Zowel productbacklog items als sprintbacklog items zijn volledig afgestemd met de productowner.",
                            Name = "Afgestemde PBL en SBL"
                        },
                        new
                        {
                            CriterionId = 34,
                            CompetenceId = 5,
                            Description = "Bekende bugs worden geadminstreerd (bijvoorbeeld door ze op te nemen in de product backlog) en het oplossen hiervan heeft een plaats gekregen in het software ontwikkelproces",
                            Name = "Bug tracking"
                        },
                        new
                        {
                            CriterionId = 35,
                            CompetenceId = 5,
                            Description = "De retrospective is uitgevoerd en heeft (indien nodig) geleid tot aanpassingen op het proces.",
                            Name = "Retro"
                        },
                        new
                        {
                            CriterionId = 36,
                            CompetenceId = 5,
                            Description = "De Definition of Done is tot in voldoende detail uitgewerkt. (DoD bevat minimaal: Code Conventies, Testscenario’s, Documentatie-eisen, Acceptatiecriteria van de Product Owner)",
                            Name = "DoD"
                        },
                        new
                        {
                            CriterionId = 37,
                            CompetenceId = 5,
                            Description = "Er wordt na elke sprint een ready to release softwareproduct (overeenkomstig definition of done)  increment opgeleverd.",
                            Name = "Increment"
                        },
                        new
                        {
                            CriterionId = 38,
                            CompetenceId = 6,
                            Description = "Er is een gedetailleerde reflectie op de verbeterpunten uit de Retrospective beschreven. (Per student beschreven in ‘Professionele Ontwikkeling’)",
                            Name = "Reflectie op verbeteringspunten"
                        },
                        new
                        {
                            CriterionId = 39,
                            CompetenceId = 6,
                            Description = "Bij aanvang zijn realistische vakinhoudelijke en persoonlijke professionele leerdoelen SMART geformuleerd. (Per student beschreven in ‘Professionele Ontwikkeling’). De student is hier actief mee aan de gang gegaan.",
                            Name = "Leerdoelen"
                        },
                        new
                        {
                            CriterionId = 40,
                            CompetenceId = 6,
                            Description = "Het werken aan professionele ontwikkeling  en de resultaten hiervan zijn aan de hand van concrete voorbeelden geïllustreerd. (Per student beschreven in ‘Professionele Ontwikkeling’)",
                            Name = "Professionele Ontwikkeling"
                        },
                        new
                        {
                            CriterionId = 41,
                            CompetenceId = 6,
                            Description = "Er is inzicht in de eigen sterktes en zwaktes. (Per student beschreven in ‘Professionele Ontwikkeling’)",
                            Name = "Sterktes en zwaktes"
                        },
                        new
                        {
                            CriterionId = 42,
                            CompetenceId = 6,
                            Description = "Er is een gedetailleerde reflectie op alle hier genoemde competenties. De reflectie is per groep, waarbij de bijdrage van de individuele student goed naar voren komt.",
                            Name = "Reflectie"
                        });
                });

            modelBuilder.Entity("Model.Form", b =>
                {
                    b.Property<int>("FormId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FormId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FormId");

                    b.ToTable("Forms");

                    b.HasData(
                        new
                        {
                            FormId = 1,
                            Name = "Software Engineering periode 2"
                        });
                });

            modelBuilder.Entity("Model.FormIndicator", b =>
                {
                    b.Property<int>("FormId")
                        .HasColumnType("int");

                    b.Property<int>("IndicatorId")
                        .HasColumnType("int");

                    b.HasKey("FormId", "IndicatorId");

                    b.HasIndex("IndicatorId");

                    b.ToTable("FormIndicators");

                    b.HasData(
                        new
                        {
                            FormId = 1,
                            IndicatorId = 1
                        },
                        new
                        {
                            FormId = 1,
                            IndicatorId = 2
                        },
                        new
                        {
                            FormId = 1,
                            IndicatorId = 3
                        });
                });

            modelBuilder.Entity("Model.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupId"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("GroupId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Model.GroupStudent", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("StudentNumber")
                        .HasColumnType("int");

                    b.HasKey("GroupId", "StudentNumber");

                    b.HasIndex("StudentNumber");

                    b.ToTable("GroupStudents");
                });

            modelBuilder.Entity("Model.Indicator", b =>
                {
                    b.Property<int>("IndicatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IndicatorId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("IndicatorId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Indicators");

                    b.HasData(
                        new
                        {
                            IndicatorId = 1,
                            Name = "Ontwikkelpunt",
                            Value = 3.0
                        },
                        new
                        {
                            IndicatorId = 2,
                            Name = "Competent",
                            Value = 7.0
                        },
                        new
                        {
                            IndicatorId = 3,
                            Name = "Voorbeeldig",
                            Value = 9.0
                        });
                });

            modelBuilder.Entity("Model.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FormId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectId");

                    b.HasIndex("FormId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            ProjectId = 1,
                            Code = "ICT.SE.OSD.PRJCT.V21",
                            Description = "De docenten beoordelen KBS-projecten en stages met behulp van het assessmentformulier. Dit formulier vult de docent in op papier of in Word door de relevante vakken te markeren. Vervolgens moet de docent zelf het cijfer berekenen (afhankelijk van de weging) en daarna moeten de cijfers handmatig ingevuld worden in Educator. Dit vereist veel handelingen en afhankelijkheid van verschillende systemen. De docenten willen dit formulier gedigitaliseerd hebben en willen dat jullie als SCRUM-team nadenken over hoe je hem/haar zoveel mogelijk tijd kunt besparen. Het zou bijvoorbeeld mooi zijn als er één systeem is dat gebruikt wordt, in plaats van meerdere systemen.",
                            FormId = 1,
                            Name = "Beoordelingssysteem"
                        },
                        new
                        {
                            ProjectId = 2,
                            Code = "ICT.SE.OSD.PRJCT.V21",
                            Description = "Als student begeleider heb je vaak veel studenten die je moet coachen. Soms is het daardoor lastig overzicht te bewaren: wanneer heb ik een student voor het laatst gesproken, hoe vaak is een student aanwezig bij de colleges, hoe zijn de cijfers van de student, welke problemen loopt hij / zij tegenaan, etc.Ook is vaak niet duidelijk welke leerdoelen de student gedurende de opleiding heeft gehad, iets dat de student begeleider graag makkelijk terug zou willen kunnen zien. De opdracht is om een systeem te ontwikkelen dat meer overzicht biedt voor de student begeleider in de studenten die hij/ zij begeleidt.",
                            FormId = 1,
                            Name = "Systeem student begeleider"
                        });
                });

            modelBuilder.Entity("Model.Rating", b =>
                {
                    b.Property<int>("AssessmentId")
                        .HasColumnType("int");

                    b.Property<int>("CriterionId")
                        .HasColumnType("int");

                    b.Property<int>("RequirementId")
                        .HasColumnType("int");

                    b.HasKey("AssessmentId", "CriterionId");

                    b.HasIndex("CriterionId");

                    b.HasIndex("RequirementId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("Model.Requirement", b =>
                {
                    b.Property<int>("RequirementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequirementId"), 1L, 1);

                    b.Property<int>("CriterionId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IndicatorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequirementId");

                    b.HasIndex("CriterionId");

                    b.HasIndex("IndicatorId");

                    b.ToTable("Requirements");
                });

            modelBuilder.Entity("Model.Student", b =>
                {
                    b.Property<int>("StudentNumber")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentNumber");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Model.Assessment", b =>
                {
                    b.HasOne("Model.Group", "Group")
                        .WithMany("Assessments")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Project", "Project")
                        .WithMany("Assessments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Model.Competence", b =>
                {
                    b.HasOne("Model.Form", "Form")
                        .WithMany("Competences")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Form");
                });

            modelBuilder.Entity("Model.Criterion", b =>
                {
                    b.HasOne("Model.Competence", "Competence")
                        .WithMany("Criteria")
                        .HasForeignKey("CompetenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competence");
                });

            modelBuilder.Entity("Model.FormIndicator", b =>
                {
                    b.HasOne("Model.Form", "Form")
                        .WithMany("FromIndicators")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Indicator", "Indicator")
                        .WithMany("FromIndicators")
                        .HasForeignKey("IndicatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Form");

                    b.Navigation("Indicator");
                });

            modelBuilder.Entity("Model.GroupStudent", b =>
                {
                    b.HasOne("Model.Group", "Group")
                        .WithMany("GroupStudents")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Student", "Student")
                        .WithMany("GroupStudents")
                        .HasForeignKey("StudentNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Model.Project", b =>
                {
                    b.HasOne("Model.Form", "Form")
                        .WithMany("Projects")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Form");
                });

            modelBuilder.Entity("Model.Rating", b =>
                {
                    b.HasOne("Model.Assessment", "Assessment")
                        .WithMany("Ratings")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Criterion", "Criterion")
                        .WithMany("Ratings")
                        .HasForeignKey("CriterionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Model.Requirement", "Requirement")
                        .WithMany("Ratings")
                        .HasForeignKey("RequirementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assessment");

                    b.Navigation("Criterion");

                    b.Navigation("Requirement");
                });

            modelBuilder.Entity("Model.Requirement", b =>
                {
                    b.HasOne("Model.Criterion", "Criterion")
                        .WithMany("Requirements")
                        .HasForeignKey("CriterionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Indicator", "Indicator")
                        .WithMany()
                        .HasForeignKey("IndicatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Criterion");

                    b.Navigation("Indicator");
                });

            modelBuilder.Entity("Model.Assessment", b =>
                {
                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("Model.Competence", b =>
                {
                    b.Navigation("Criteria");
                });

            modelBuilder.Entity("Model.Criterion", b =>
                {
                    b.Navigation("Ratings");

                    b.Navigation("Requirements");
                });

            modelBuilder.Entity("Model.Form", b =>
                {
                    b.Navigation("Competences");

                    b.Navigation("FromIndicators");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Model.Group", b =>
                {
                    b.Navigation("Assessments");

                    b.Navigation("GroupStudents");
                });

            modelBuilder.Entity("Model.Indicator", b =>
                {
                    b.Navigation("FromIndicators");
                });

            modelBuilder.Entity("Model.Project", b =>
                {
                    b.Navigation("Assessments");
                });

            modelBuilder.Entity("Model.Requirement", b =>
                {
                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("Model.Student", b =>
                {
                    b.Navigation("GroupStudents");
                });
#pragma warning restore 612, 618
        }
    }
}
