// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Service.Database;

#nullable disable

namespace Service.Database.Migrations
{
    [DbContext(typeof(AssessmentContext))]
    [Migration("20220531094952_ReleaseSeed")]
    partial class ReleaseSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Model.Assessment", b =>
                {
                    b.Property<int>("AssessmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssessmentId"), 1L, 1);

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("AssessmentId");

                    b.HasIndex("GroupId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Assessments");
                });

            modelBuilder.Entity("Model.Competence", b =>
                {
                    b.Property<int>("CompetenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompetenceId"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FormId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("CompetenceId");

                    b.HasIndex("FormId");

                    b.ToTable("Competences");

                    b.HasData(
                        new
                        {
                            CompetenceId = 1,
                            Evidence = "Product Backlog\r\nSprint Backlog\r\nBeschreven Business Case (eventueel als inleiding bij het functioneel ontwerp)\r\nAnder bewijsmateriaal zoals: interviewverslagen, schetsen van UML-diagrammen, foto’s van schetsen op whiteboards\r\nPortfolio: Reflectie op competentie Analyse & Onderzoek",
                            FormId = 1,
                            Name = "Analyseren",
                            Weight = 0.10000000000000001
                        },
                        new
                        {
                            CompetenceId = 2,
                            Evidence = "Sprint review\r\nSprint planning\r\nProduct backlog\r\nSprint backlog\r\nDefinition of Done\r\nPortfolio: Reflectie op competentie Advies en Communicatie",
                            FormId = 1,
                            Name = "Adviseren",
                            Weight = 0.10000000000000001
                        },
                        new
                        {
                            CompetenceId = 3,
                            Evidence = "Het functioneel ontwerp - Usecase/Userstory diagram, Domeinmodel en evt. andere diagrammen\r\nHet technisch ontwerp  – ERD, (UML-)diagrammen\r\nTestscenario’s (evt. in het functioneel ontwerp)\r\nPortfolio: Reflectie op competentie Ontwerp en Architectuur",
                            FormId = 1,
                            Name = "Ontwerpen",
                            Weight = 0.20000000000000001
                        },
                        new
                        {
                            CompetenceId = 4,
                            Evidence = "Broncode\r\nTestscenario’s (evt. in het functioneel ontwerp)\r\nTestprocedure\r\nTestrapportages\r\nTestprocedure\r\nUnit testen\r\nCode conventies\r\nInstallatiehandleiding\r\nPortfolio: Reflectie op competentie Realisatie en Testen ",
                            FormId = 1,
                            Name = "Realiseren",
                            Weight = 0.29999999999999999
                        },
                        new
                        {
                            CompetenceId = 5,
                            Evidence = "Dagelijkse Scrum\r\nSprint review\r\nRetrospective \r\nProduct backlog\r\nSprint backlog\r\nBurn down charts\r\nPortfolio: reflective op competentie management en beheer ",
                            FormId = 1,
                            Name = "Beheren",
                            Weight = 0.20000000000000001
                        },
                        new
                        {
                            CompetenceId = 6,
                            Evidence = "Retrospective\r\nPortfolio: Hoofdstuk 'Professionele ontwikkeling'",
                            FormId = 1,
                            Name = "Professionele Ontwikkeling",
                            Weight = 0.10000000000000001
                        });
                });

            modelBuilder.Entity("Model.Criterion", b =>
                {
                    b.Property<int>("CriterionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CriterionId"), 1L, 1);

                    b.Property<int>("CompetenceId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CriterionId");

                    b.HasIndex("CompetenceId");

                    b.ToTable("Criteria");

                    b.HasData(
                        new
                        {
                            CriterionId = 1,
                            CompetenceId = 1,
                            Description = "Alle gerealiseerde sprint backlog items zijn terug te vinden in het functioneel ontwerp. Denk onder andere aan een bijgewerkt domeinmodel  en use case diagram. De uitgewerkte backlog items zijn in het functioneel ontwerp terug te vinden als uitgewerkte user-stories. Waar zinvol is het functioneel ontwerp ondersteunt met activiteitendiagrammen, toestandsdiagrammen en sequentiediagrammen.",
                            Name = "Methodische requirement analyse"
                        },
                        new
                        {
                            CriterionId = 2,
                            CompetenceId = 1,
                            Description = "De business case (de rechtvaardiging van het project, de probleemstelling, de opdracht) is beschreven en afgestemd met de opdrachtgever.",
                            Name = "Afgestemde BC"
                        },
                        new
                        {
                            CriterionId = 3,
                            CompetenceId = 1,
                            Description = "De productbacklog wordt continue aangevuld met items die tijdens de analyse (bijvoorbeeld tijdens sprint planning meetings) van het op te lossen ‘probleem’, naar voren komen.",
                            Name = "Continu aangevulde PBL"
                        },
                        new
                        {
                            CriterionId = 4,
                            CompetenceId = 1,
                            Description = "Sprintbacklog items zijn tot in voldoende detail geanalyseerd en systematisch uitgewerkt. (Voldoende detail = Gemaakte keuzes worden door alle belanghebbenden begrepen). Hulpmiddelen daarbij zijn o.a.: Userstories incl. scherm/interactie/navigatie-ontwerp, Domeinmodel, Usecase/Userstory diagram.",
                            Name = "Gedetailleerde BLI"
                        },
                        new
                        {
                            CriterionId = 5,
                            CompetenceId = 2,
                            Description = "De product owner is gedurende alle sprints tijdig en volledig geinformeerd.",
                            Name = "Geïnformeerde PO"
                        },
                        new
                        {
                            CriterionId = 6,
                            CompetenceId = 2,
                            Description = "Er zijn geschikte communicatievormen gekozen en daadwerkelijk toegepast met als doel adviezen te geven.",
                            Name = "Communicatievormen"
                        },
                        new
                        {
                            CriterionId = 7,
                            CompetenceId = 2,
                            Description = "Alle documenten zijn geschreven in correct Nederlands, zijn helder en duidelijk. ",
                            Name = "Correct Nederlands"
                        },
                        new
                        {
                            CriterionId = 8,
                            CompetenceId = 2,
                            Description = "Het scrum team denkt mee met de product owner (denk aan sprint planning). Het scrum team komt bijvoorbeeld met alternatieven voor wensen van de productowner die minder tijd kosten om te implementeren.",
                            Name = "Meedenken met PO"
                        },
                        new
                        {
                            CriterionId = 9,
                            CompetenceId = 3,
                            Description = "Alle gerealiseerde sprint backlog items zijn terug te vinden in het functioneel ontwerp. Denk onder andere aan een bijgewerkt domeinmodel en use case diagram. De uitgewerkte backlog items zijn in het functioneel ontwerp terug te vinden als uitgewerkte user-stories. Waar zinvol is het functioneel ontwerp ondersteunt met activiteitendiagrammen, toestandsdiagrammen en sequentiediagrammen.",
                            Name = "BLI in FO"
                        },
                        new
                        {
                            CriterionId = 10,
                            CompetenceId = 3,
                            Description = "Tijdens elke sprint wordt het ontwerp bijgewerkt. Denk bijvoorbeeld aan het toevoegen en/of uitbreiden van klassen in de verschillende klassendiagrammen. Belangrijke technische aspecten worden uitgelegd en ondersteund door (UML-)diagrammen.",
                            Name = "Bijwerken van ontwerp"
                        },
                        new
                        {
                            CriterionId = 11,
                            CompetenceId = 3,
                            Description = "Het functioneel ontwerp en het technisch ontwerp zijn volledig consistent met elkaar.",
                            Name = "Consistent FO en TO"
                        },
                        new
                        {
                            CriterionId = 12,
                            CompetenceId = 3,
                            Description = "Tijdens elke sprint wordt het ERD bijgewerkt (indien van toepassing). Keuzes voor het db-ontwerp (bijv. een extra index) worden toegelicht. De naamgeving van de tabellen en kollomen van de database zijn consistent met de naamgeving zoals gebruikt in het domeinmodel",
                            Name = "Bijgewerkt ERD"
                        },
                        new
                        {
                            CriterionId = 13,
                            CompetenceId = 3,
                            Description = "De gevolgde architectuur en ontwerpkeuzes zijn in het technisch ontwerp toegelicht en gemotiveerd.",
                            Name = "Toegelicht TO"
                        },
                        new
                        {
                            CriterionId = 14,
                            CompetenceId = 3,
                            Description = "In het ontwerp is alle benodige informatie opgenomen om een nieuw teamlid snel op weg te helpen met het realiseren van de software. Naast de eerder genoemde aspecten kun je daarbij ook denken aan het vermelden van gebruikte tools, frameworks en verwijzingingen naar bruikbaar studiemateriaal.",
                            Name = "Zelfstandig ontwerp"
                        },
                        new
                        {
                            CriterionId = 15,
                            CompetenceId = 3,
                            Description = "Voor ieder gerealiseerd item is een uitgebreide testset beschreven, waarmee de kwaliteit van de gerealiseerde software aangetoond kan worden.",
                            Name = "Testset voor ieder BLI"
                        },
                        new
                        {
                            CriterionId = 16,
                            CompetenceId = 4,
                            Description = "Alle broncode is op consistente wijze van commentaar voorzien.",
                            Name = "Comments"
                        },
                        new
                        {
                            CriterionId = 17,
                            CompetenceId = 4,
                            Description = "Code coventies zijn beschreven en nageleefd.",
                            Name = "Coding conventions"
                        },
                        new
                        {
                            CriterionId = 18,
                            CompetenceId = 4,
                            Description = "De code is consistent  met het opgestelde ontwerp.",
                            Name = "Consistentie"
                        },
                        new
                        {
                            CriterionId = 19,
                            CompetenceId = 4,
                            Description = "Er is een testprocedure beschreven waarin o.a. vastligt wie, wat en wanneer test.",
                            Name = "Testprocedure"
                        },
                        new
                        {
                            CriterionId = 20,
                            CompetenceId = 4,
                            Description = "De student rapporteert over unit-testen en overige testen.",
                            Name = "Testrapportage"
                        },
                        new
                        {
                            CriterionId = 21,
                            CompetenceId = 4,
                            Description = "Waar zinvol, zijn unit-testen toegepast.",
                            Name = "Unit tests"
                        },
                        new
                        {
                            CriterionId = 22,
                            CompetenceId = 4,
                            Description = "Alle namen in de code gebruiken een consistente vocabulair. Namen in de code beschrijven de intentie van de code.",
                            Name = "Self-documenting code"
                        },
                        new
                        {
                            CriterionId = 23,
                            CompetenceId = 4,
                            Description = "Formattering geeft een perfect inzicht in de beoogde structuur.",
                            Name = "Formatting"
                        },
                        new
                        {
                            CriterionId = 24,
                            CompetenceId = 4,
                            Description = "De code in methodes is voor de gewenste functionaliteit eenvoudig van opzet.",
                            Name = "Refactoring"
                        },
                        new
                        {
                            CriterionId = 25,
                            CompetenceId = 4,
                            Description = "De code is modulair opgezet en daardoor makkelijk te onderhouden, te lezen en te unit testen.",
                            Name = "Scalability"
                        },
                        new
                        {
                            CriterionId = 26,
                            CompetenceId = 5,
                            Description = "Tijdens elke Sprint Review wordt duidelijk aangegeven welke items in de sprint opgenomen zijn en welke items daarvan wel dan wel niet zijn gerealiseerd. Per gerealiseerd item wordt een demo gegeven.",
                            Name = "Opgenomen items in SR"
                        },
                        new
                        {
                            CriterionId = 27,
                            CompetenceId = 5,
                            Description = "Tijdens elke Sprint Review wordt de burn down chart besproken. Wat was de geplande velocity en waar is het team op uitgekomen?",
                            Name = "Besproken BDC in SR"
                        },
                        new
                        {
                            CriterionId = 28,
                            CompetenceId = 5,
                            Description = "Scrum stand-ups worden dagelijks en getimeboxed (bijv. max 15 minuten) uitgevoerd en zijn navolgbaar (foto’s, reflectie) voor de assessoren.",
                            Name = "Daily standup"
                        },
                        new
                        {
                            CriterionId = 29,
                            CompetenceId = 5,
                            Description = "Er is een geschikte tool en systematiek geselecteerd voor het managen van de product backlog items. Dit wordt in het reflectieverslag besproken.",
                            Name = "Tool voor BLI"
                        },
                        new
                        {
                            CriterionId = 30,
                            CompetenceId = 5,
                            Description = "Er is een geschikte tool en systematiek geselecteerd voor het samenwerken aan en het beheren van de broncode. Dit wordt in het reflectieverslag besproken.",
                            Name = "Version control system"
                        },
                        new
                        {
                            CriterionId = 31,
                            CompetenceId = 5,
                            Description = "Productbacklog items zijn in voldoende detail en consistent beschreven in de product backlog..",
                            Name = "Gedetaileerde BLI"
                        },
                        new
                        {
                            CriterionId = 32,
                            CompetenceId = 5,
                            Description = "Productbacklog items met een hoge prioriteit zijn al duidelijk verder uitgewerkt in vergelijking met items met een lage prioriteit.",
                            Name = "Geprioriteerde BLI"
                        },
                        new
                        {
                            CriterionId = 33,
                            CompetenceId = 5,
                            Description = "Zowel productbacklog items als sprintbacklog items zijn volledig afgestemd met de productowner.",
                            Name = "Afgestemde PBL en SBL"
                        },
                        new
                        {
                            CriterionId = 34,
                            CompetenceId = 5,
                            Description = "Bekende bugs worden geadminstreerd (bijvoorbeeld door ze op te nemen in de product backlog) en het oplossen hiervan heeft een plaats gekregen in het software ontwikkelproces",
                            Name = "Bug tracking"
                        },
                        new
                        {
                            CriterionId = 35,
                            CompetenceId = 5,
                            Description = "De retrospective is uitgevoerd en heeft (indien nodig) geleid tot aanpassingen op het proces.",
                            Name = "Retro"
                        },
                        new
                        {
                            CriterionId = 36,
                            CompetenceId = 5,
                            Description = "De Definition of Done is tot in voldoende detail uitgewerkt. (DoD bevat minimaal: Code Conventies, Testscenario’s, Documentatie-eisen, Acceptatiecriteria van de Product Owner)",
                            Name = "DoD"
                        },
                        new
                        {
                            CriterionId = 37,
                            CompetenceId = 5,
                            Description = "Er wordt na elke sprint een ready to release softwareproduct (overeenkomstig definition of done)  increment opgeleverd.",
                            Name = "Increment"
                        },
                        new
                        {
                            CriterionId = 38,
                            CompetenceId = 6,
                            Description = "Er is een gedetailleerde reflectie op de verbeterpunten uit de Retrospective beschreven. (Per student beschreven in ‘Professionele Ontwikkeling’)",
                            Name = "Reflectie op verbeteringspunten"
                        },
                        new
                        {
                            CriterionId = 39,
                            CompetenceId = 6,
                            Description = "Bij aanvang zijn realistische vakinhoudelijke en persoonlijke professionele leerdoelen SMART geformuleerd. (Per student beschreven in ‘Professionele Ontwikkeling’). De student is hier actief mee aan de gang gegaan.",
                            Name = "Leerdoelen"
                        },
                        new
                        {
                            CriterionId = 40,
                            CompetenceId = 6,
                            Description = "Het werken aan professionele ontwikkeling  en de resultaten hiervan zijn aan de hand van concrete voorbeelden geïllustreerd. (Per student beschreven in ‘Professionele Ontwikkeling’)",
                            Name = "Professionele Ontwikkeling"
                        },
                        new
                        {
                            CriterionId = 41,
                            CompetenceId = 6,
                            Description = "Er is inzicht in de eigen sterktes en zwaktes. (Per student beschreven in ‘Professionele Ontwikkeling’)",
                            Name = "Sterktes en zwaktes"
                        },
                        new
                        {
                            CriterionId = 42,
                            CompetenceId = 6,
                            Description = "Er is een gedetailleerde reflectie op alle hier genoemde competenties. De reflectie is per groep, waarbij de bijdrage van de individuele student goed naar voren komt.",
                            Name = "Reflectie"
                        });
                });

            modelBuilder.Entity("Model.Form", b =>
                {
                    b.Property<int>("FormId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FormId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FormId");

                    b.ToTable("Forms");

                    b.HasData(
                        new
                        {
                            FormId = 1,
                            Name = "Software Engineering periode 2"
                        });
                });

            modelBuilder.Entity("Model.FormIndicator", b =>
                {
                    b.Property<int>("FormId")
                        .HasColumnType("int");

                    b.Property<int>("IndicatorId")
                        .HasColumnType("int");

                    b.HasKey("FormId", "IndicatorId");

                    b.HasIndex("IndicatorId");

                    b.ToTable("FormIndicators");

                    b.HasData(
                        new
                        {
                            FormId = 1,
                            IndicatorId = 1
                        },
                        new
                        {
                            FormId = 1,
                            IndicatorId = 2
                        },
                        new
                        {
                            FormId = 1,
                            IndicatorId = 3
                        });
                });

            modelBuilder.Entity("Model.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupId"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("GroupId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Model.GroupStudent", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("StudentNumber")
                        .HasColumnType("int");

                    b.HasKey("GroupId", "StudentNumber");

                    b.HasIndex("StudentNumber");

                    b.ToTable("GroupStudents");
                });

            modelBuilder.Entity("Model.Indicator", b =>
                {
                    b.Property<int>("IndicatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IndicatorId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("IndicatorId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Indicators");

                    b.HasData(
                        new
                        {
                            IndicatorId = 1,
                            Name = "Ontwikkelpunt",
                            Value = 3.0
                        },
                        new
                        {
                            IndicatorId = 2,
                            Name = "Competent",
                            Value = 7.0
                        },
                        new
                        {
                            IndicatorId = 3,
                            Name = "Voorbeeldig",
                            Value = 9.0
                        });
                });

            modelBuilder.Entity("Model.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FormId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectId");

                    b.HasIndex("FormId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            ProjectId = 1,
                            Code = "ICT.SE.OSD.PRJCT.V21",
                            Description = "De docenten beoordelen KBS-projecten en stages met behulp van het assessmentformulier. Dit formulier vult de docent in op papier of in Word door de relevante vakken te markeren. Vervolgens moet de docent zelf het cijfer berekenen (afhankelijk van de weging) en daarna moeten de cijfers handmatig ingevuld worden in Educator. Dit vereist veel handelingen en afhankelijkheid van verschillende systemen. De docenten willen dit formulier gedigitaliseerd hebben en willen dat jullie als SCRUM-team nadenken over hoe je hem/haar zoveel mogelijk tijd kunt besparen. Het zou bijvoorbeeld mooi zijn als er één systeem is dat gebruikt wordt, in plaats van meerdere systemen.",
                            FormId = 1,
                            Name = "Beoordelingssysteem"
                        },
                        new
                        {
                            ProjectId = 2,
                            Code = "ICT.SE.OSD.PRJCT.V21",
                            Description = "Als student begeleider heb je vaak veel studenten die je moet coachen. Soms is het daardoor lastig overzicht te bewaren: wanneer heb ik een student voor het laatst gesproken, hoe vaak is een student aanwezig bij de colleges, hoe zijn de cijfers van de student, welke problemen loopt hij / zij tegenaan, etc.Ook is vaak niet duidelijk welke leerdoelen de student gedurende de opleiding heeft gehad, iets dat de student begeleider graag makkelijk terug zou willen kunnen zien. De opdracht is om een systeem te ontwikkelen dat meer overzicht biedt voor de student begeleider in de studenten die hij/ zij begeleidt.",
                            FormId = 1,
                            Name = "Systeem student begeleider"
                        });
                });

            modelBuilder.Entity("Model.Rating", b =>
                {
                    b.Property<int>("AssessmentId")
                        .HasColumnType("int");

                    b.Property<int>("CriterionId")
                        .HasColumnType("int");

                    b.Property<int>("RequirementId")
                        .HasColumnType("int");

                    b.HasKey("AssessmentId", "CriterionId");

                    b.HasIndex("CriterionId");

                    b.HasIndex("RequirementId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("Model.Requirement", b =>
                {
                    b.Property<int>("RequirementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequirementId"), 1L, 1);

                    b.Property<int>("CriterionId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IndicatorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequirementId");

                    b.HasIndex("CriterionId");

                    b.HasIndex("IndicatorId");

                    b.ToTable("Requirements");

                    b.HasData(
                        new
                        {
                            RequirementId = 1,
                            CriterionId = 1,
                            Description = "Bereidt gesprekken niet voor. Koppelt niet terug aan betrokkenen. Maakt geen gebruik van UML of vergelijkbare diagrammen. Verdiept zich niet in het domein. Houdt geen rekening met niet-functionele eisen.",
                            IndicatorId = 1
                        },
                        new
                        {
                            RequirementId = 2,
                            CriterionId = 1,
                            Description = "Bereidt gesprekken enigszins voor en koppelt in enige mate terug aan betrokkenen. Maakt gebruik van hooguit één soort diagram (bijv. domeinmodel of use case diagram). Verdiept zich enigszins in het domein, bijvoorbeeld door het bestuderen van vergelijkbare systemen. Houdt impliciet rekening met niet-functionele eisen.",
                            IndicatorId = 2
                        },
                        new
                        {
                            RequirementId = 3,
                            CriterionId = 1,
                            Description = "Bereidt gesprekken goed voor en koppelt de resultaten terug aan betrokkenen Maakt gebruik van verschillende UML diagrammen om het probleem vanuit verschillende gezichtspunten te benaderen. Kiest de juiste diagrammen voor de context. Verdiept zich uitgebreid in het domein en gebruikt daarvoor verschillende bronnen. Houdt expliciet rekening met niet-functionele eisen.",
                            IndicatorId = 3
                        },
                        new
                        {
                            RequirementId = 4,
                            CriterionId = 2,
                            Description = "De student voert de opdracht uit, echter zonder na te denken over de achterliggende probleemstelling.",
                            IndicatorId = 1
                        },
                        new
                        {
                            RequirementId = 5,
                            CriterionId = 2,
                            Description = "De student is zich bewust van het onderliggende probleem voor de opdracht en legt dit vast.",
                            IndicatorId = 2
                        },
                        new
                        {
                            RequirementId = 6,
                            CriterionId = 2,
                            Description = "De student werkt de business case uit en toont aan dat de gekozen oplossing daarmee in overeenstemming is. De student heeft alternatieven in overweging genomen en besproken met de opdrachtgever.",
                            IndicatorId = 3
                        },
                        new
                        {
                            RequirementId = 7,
                            CriterionId = 3,
                            Description = "Het team is niet actief bezig met de product backlog.",
                            IndicatorId = 1
                        },
                        new
                        {
                            RequirementId = 8,
                            CriterionId = 3,
                            Description = "Tijdens de sprint planning meetings, worden er veelvuldig nieuwe items vastgelegd. ",
                            IndicatorId = 2
                        },
                        new
                        {
                            RequirementId = 9,
                            CriterionId = 3,
                            Description = "Tijdens de sprint planning meetings, worden er veelvuldig nieuwe items vastgelegd. De items worden tijdens en/of na de sprint planning meeting met de product owner besproken en afhankelijk van de prioriteit gedetailleerd.",
                            IndicatorId = 3
                        },
                        new
                        {
                            RequirementId = 10,
                            CriterionId = 4,
                            Description = "Sprintbacklog items worden kort besproken tijdens een sprint planning meeting en op basis daarvan wordt een inschatting gemaakt voor de benodigde inspanning. Als een docent er naar vraagt, blijkt echter dat een ieder zijn eigen interpretatie geeft aan een item.",
                            IndicatorId = 1
                        },
                        new
                        {
                            RequirementId = 11,
                            CriterionId = 4,
                            Description = "Sprintbacklog items worden  besproken tijdens een sprint planning. Diepgang ontbreekt echter nog.",
                            IndicatorId = 2
                        },
                        new
                        {
                            RequirementId = 12,
                            CriterionId = 4,
                            Description = "Zowel product owner als teamleden weten voor ieder item nauwkeurig wat er gerealiseerd gaat worden. Onafhankelijk van elkaar zouden ze tot een vergelijkbare uitwerking komen. Tijdens de sprint planning meeting is er uitgebreid gebruik gemaakt van bijvoorbeeld het white board, om zaken duidelijk te maken, en alternatieven te bespreken. Het kan ook zijn dat items al eerder tot in voldoende detail zijn uitgewerkt, zodat deze minder aandacht behoeven tijdens de meeting.",
                            IndicatorId = 3
                        },
                        new
                        {
                            RequirementId = 13,
                            CriterionId = 5,
                            Description = "Dit gebeurt niet.",
                            IndicatorId = 1
                        },
                        new
                        {
                            RequirementId = 14,
                            CriterionId = 5,
                            Description = "De studenten informeren de product owner middels e-mail. Initiatief voor bespreken van heikele punten ligt nog voor een groot deel bij de product owner.",
                            IndicatorId = 2
                        },
                        new
                        {
                            RequirementId = 15,
                            CriterionId = 5,
                            Description = "De studenten informeren de product owner gedurende de sprints. Verschillende communicatievormen worden gebruikt, zoals bijvoorbeeld telefoon en e-mail. Er is goed overlegd indien een item bijvoorbeeld te veel tijd dreigt te vragen of indien er alternatieven besproken dienen te worden.",
                            IndicatorId = 3
                        },
                        new
                        {
                            RequirementId = 16,
                            CriterionId = 6,
                            Description = "Communicatie is hoofdzakelijk mondeling, tijdens de daarvoor geplande meetings.",
                            IndicatorId = 1
                        },
                        new
                        {
                            RequirementId = 17,
                            CriterionId = 6,
                            Description = "Studenten gebruiken tijdens meetings meerdere zinvolle communicatiemiddelen.",
                            IndicatorId = 2
                        },
                        new
                        {
                            RequirementId = 18,
                            CriterionId = 6,
                            Description = "Studenten gebruiken tijdens meetings meerdere zinvolle communicatiemiddelen en stimuleren elkaar en de product owner om input te geven. Incidenteel worden er demos (bijv. voorstel schermlay-out) voorbereid om advies te kunnen geven.",
                            IndicatorId = 3
                        },
                        new
                        {
                            RequirementId = 19,
                            CriterionId = 7,
                            Description = "De documenten bevatten schrijffouten en zijn moeilijk te volgen.",
                            IndicatorId = 1
                        },
                        new
                        {
                            RequirementId = 20,
                            CriterionId = 7,
                            Description = "De documenten bevatten nauwelijks schrijffouten. De documenten zijn duidelijk.",
                            IndicatorId = 2
                        },
                        new
                        {
                            RequirementId = 21,
                            CriterionId = 7,
                            Description = "De documenten bevatten nauwelijks schrijffouten. De lezer wordt bij de hand genomen, de hoofd- en bijzaken worden heel goed onderscheiden.",
                            IndicatorId = 3
                        },
                        new
                        {
                            RequirementId = 22,
                            CriterionId = 8,
                            Description = "De studenten leggen het initiatief volledig bij de product owner.",
                            IndicatorId = 1
                        },
                        new
                        {
                            RequirementId = 23,
                            CriterionId = 8,
                            Description = "De studenten denken gevraagd en ongevraagd  mee met de product owner. Het team komt met alternatieven voor de product owner.",
                            IndicatorId = 2
                        },
                        new
                        {
                            RequirementId = 24,
                            CriterionId = 8,
                            Description = "De studenten denken gevraagd en ongevraagd mee met de product owner. Alternatieven worden goed uitgelegd zodat de product owner een weloverwogen keuze kan maken. Tijdens sprint planning meetings zijn de studenten goed voorbereid zodat binnen de beschikbare tijd, alternatieven gepresenteerd kunnen worden.",
                            IndicatorId = 3
                        },
                        new
                        {
                            RequirementId = 25,
                            CriterionId = 9,
                            Description = "Het domeinmodel en/of use case diagram ontbreken of zijn van slechte kwaliteit. Essentiele user-stories zijn niet volledig uitgewerkt.",
                            IndicatorId = 1
                        },
                        new
                        {
                            RequirementId = 26,
                            CriterionId = 9,
                            Description = "Het domeinmodel en use case diagram zijn correct, consistent met elkaar, en zonodige opgesplitst in meerdere diagrammen. Alle essentiële user-stories zijn volledig uitgewerkt.",
                            IndicatorId = 2
                        },
                        new
                        {
                            RequirementId = 27,
                            CriterionId = 9,
                            Description = "Een lezer krijgt op basis van het functioneel ontwerp snel inzicht in de geleverde functionaliteit. Het domeinmodel en use case diagram zijn correct, consistent met elkaar, en zonodig opgesplitst in meerdere diagrammen. Alle essentiële user-stories zijn volledig uitgewerkt.Triviale user-stories worden genoemd, maar niet tot in detail uitgewerkt. Waar zinvol is het functioneel ontwerp ondersteunt met activiteitendiagrammen, toestandsdiagrammen en sequentiediagrammen.",
                            IndicatorId = 3
                        },
                        new
                        {
                            RequirementId = 28,
                            CriterionId = 10,
                            Description = "Wordt niet structureel gedaan.",
                            IndicatorId = 1
                        },
                        new
                        {
                            RequirementId = 29,
                            CriterionId = 10,
                            Description = "Wordt structureel gedaan, maar beperkt zich tot hoofdlijnen.",
                            IndicatorId = 2
                        },
                        new
                        {
                            RequirementId = 30,
                            CriterionId = 10,
                            Description = "Wordt structureel gedaan. Na afloop van iedere sprint is het ontwerp ook echt af, dus alle belangrijke tecnische aspecten worden meegenomen en niet uitgesteld tot de laatste sprint.",
                            IndicatorId = 3
                        },
                        new
                        {
                            RequirementId = 31,
                            CriterionId = 11,
                            Description = "Het functioneel ontwerp en het technisch ontwerp zijn niet volledig en/of niet consistent met elkaar.",
                            IndicatorId = 1
                        },
                        new
                        {
                            RequirementId = 32,
                            CriterionId = 11,
                            Description = "Het functioneel ontwerp en het technisch ontwerp zijn volledig en consistent met elkaar.",
                            IndicatorId = 2
                        },
                        new
                        {
                            RequirementId = 33,
                            CriterionId = 11,
                            Description = "Het functioneel ontwerp en het technisch ontwerp zijn volledig en consistent met elkaar. Elementen uit functioneel ontwerp zijn eenvoudig te traceren in het technisch ontwerp, bijvoorbeeld door consistente naamgeving.",
                            IndicatorId = 3
                        },
                        new
                        {
                            RequirementId = 34,
                            CriterionId = 12,
                            Description = "Het ERD is na afloop van een sprint niet consistent met de gerealiseerde database.",
                            IndicatorId = 1
                        },
                        new
                        {
                            RequirementId = 35,
                            CriterionId = 12,
                            Description = "Het ERD is na afloop consistent met de gerealiseerde database. Keuzes voor het db-ontwerp (bijv. een extra index) worden toegelicht.",
                            IndicatorId = 2
                        },
                        new
                        {
                            RequirementId = 36,
                            CriterionId = 12,
                            Description = "Het ERD is na afloop consistent met de gerealiseerde database. Keuzes voor het db-ontwerp (bijv. een extra index) worden toegelicht. De naamgeving van de tabellen en kollomen van de database zijn consistent met de naamgeving zoals gebruikt in het domeinmodel.",
                            IndicatorId = 3
                        },
                        new
                        {
                            RequirementId = 37,
                            CriterionId = 13,
                            Description = "Het technisch ontwerp ondersteunt een ontwikkelaar niet of nauwelijks. Het technisch ontwerp bestaat dan bijvoorbeeld slechts uit een klassendiagram waarin alle klassen en relaties opgesomd worden.",
                            IndicatorId = 1
                        },
                        new
                        {
                            RequirementId = 38,
                            CriterionId = 13,
                            Description = "Het technisch ontwerp laat duidelijk de architectuur van het systeem naar voren komen. Bijvoorbeeld door aan te geven welke klassen in welke systeemlagen zijn opgenomen. Essentiële ontwerpbeslissingen worden uitgelegd en ondersteund met UML-diagrammen.",
                            IndicatorId = 2
                        },
                        new
                        {
                            RequirementId = 39,
                            CriterionId = 13,
                            Description = "Het technisch ontwerp laat duidelijk de architectuur van het systeem naar voren komen. Bijvoorbeeld door aan te geven welke klassen in welke systeemlagen zijn opgenomen. Essentiele ontwerpbeslissingen worden uitgelegd en ondersteund met UML-diagrammen. De lezer wordt bij de hand genomen door het ontwerp eerst op hoofdlijnen te schetsen en daarna in te zoomen op essentiële details.",
                            IndicatorId = 3
                        },
                        new
                        {
                            RequirementId = 40,
                            CriterionId = 14,
                            Description = "Niet gedaan.",
                            IndicatorId = 1
                        },
                        new
                        {
                            RequirementId = 41,
                            CriterionId = 14,
                            Description = "Summier gedaan, bijvoorbeeld slechts een opsomming gegeven van gebruikte tools en frameworks.",
                            IndicatorId = 2
                        },
                        new
                        {
                            RequirementId = 42,
                            CriterionId = 14,
                            Description = "Alles wat een ontwikkelaar snel op weg kan helpen en relatief weinig tijd kost om te beschrijven, is in het ontwerp opgenomen. Denk bijvoorbeeld aan handleidingen voor frameworks waarnaar verwezen wordt, of bijvoorbeeld problemen met frameworks waar het team tegenaan gelopen is en de oplossing daarvoor.",
                            IndicatorId = 3
                        },
                        new
                        {
                            RequirementId = 43,
                            CriterionId = 15,
                            Description = "Niet voor alle gerealiseerde items is een testset beschreven.",
                            IndicatorId = 1
                        },
                        new
                        {
                            RequirementId = 44,
                            CriterionId = 15,
                            Description = "Er zijn testscenario’s voor ieder item opgenomen. Er is echter geen rekening gehouden met ‘alle’ mogelijk scenario’s. Vaak wordt voor een item alleen het ‘happy day scenario’ beschreven.",
                            IndicatorId = 2
                        },
                        new
                        {
                            RequirementId = 45,
                            CriterionId = 15,
                            Description = "Voor alle gerealiseerde items is een testset beschreven. Over de testsets is goed nagedacht, alle denkbare scenarios waarop een item problemen zou kunnen geven zijn opgenomen als testgeval. De kwaliteit van het systeem wordt hiermee goed geborgd.",
                            IndicatorId = 3
                        },
                        new
                        {
                            RequirementId = 46,
                            CriterionId = 16,
                            Description = "Geen commentaar in broncode opgenomen.",
                            IndicatorId = 1
                        },
                        new
                        {
                            RequirementId = 47,
                            CriterionId = 16,
                            Description = "Daar waar zinvol, commentaar opgenomen in broncode. Echter niet op consistente wijze.",
                            IndicatorId = 2
                        },
                        new
                        {
                            RequirementId = 48,
                            CriterionId = 16,
                            Description = "Daar waar zinvol, commentaar opgenomen in broncode. Op consistente wijze gedaan.",
                            IndicatorId = 3
                        },
                        new
                        {
                            RequirementId = 49,
                            CriterionId = 17,
                            Description = "Geen code conventies toegepast.",
                            IndicatorId = 1
                        },
                        new
                        {
                            RequirementId = 50,
                            CriterionId = 17,
                            Description = "Code conventies toegepast, echter niet beschreven.",
                            IndicatorId = 2
                        },
                        new
                        {
                            RequirementId = 51,
                            CriterionId = 17,
                            Description = "Code conventeis toegepast en beschreven.",
                            IndicatorId = 3
                        },
                        new
                        {
                            RequirementId = 52,
                            CriterionId = 18,
                            Description = "Keuzes uit het ontwerp zijn niet terug te vinden in broncode.",
                            IndicatorId = 1
                        },
                        new
                        {
                            RequirementId = 53,
                            CriterionId = 18,
                            Description = "Keuzes uit het ontwerp zijn terug te vinden in de broncode, alleen sluiten de gebruikte termen (bijv. klassennamen) niet goed op elkaar aan.",
                            IndicatorId = 2
                        },
                        new
                        {
                            RequirementId = 54,
                            CriterionId = 18,
                            Description = "Keuzes uit het ontwerp zijn volledig en consistent gerealiseerd in broncode.",
                            IndicatorId = 3
                        },
                        new
                        {
                            RequirementId = 55,
                            CriterionId = 19,
                            Description = "Geen testprocedure aanwezig.",
                            IndicatorId = 1
                        },
                        new
                        {
                            RequirementId = 56,
                            CriterionId = 19,
                            Description = "Er is een testprocedure beschreven waarin vastligt wie, wat en wanneer test.",
                            IndicatorId = 2
                        },
                        new
                        {
                            RequirementId = 57,
                            CriterionId = 19,
                            Description = "Testprocedure is uitgebreid beschreven (soorten testen, input voor evt. testers, manier waarop bugs gemeld worden, etcetera)",
                            IndicatorId = 3
                        },
                        new
                        {
                            RequirementId = 58,
                            CriterionId = 20,
                            Description = "Geen testrapportage aanwezig",
                            IndicatorId = 1
                        },
                        new
                        {
                            RequirementId = 59,
                            CriterionId = 20,
                            Description = "Testrapportage is globaal beschreven.",
                            IndicatorId = 2
                        },
                        new
                        {
                            RequirementId = 60,
                            CriterionId = 20,
                            Description = "Uitgebreide testrapportage aanwezig. O.a. duidelijk wie, wat, wanneer getest heeft en welke bugs in welke stadia gevonden zijn.",
                            IndicatorId = 3
                        },
                        new
                        {
                            RequirementId = 61,
                            CriterionId = 21,
                            Description = "Geen unit-testen toegepast, terwijl dit wel zinvol was geweest.",
                            IndicatorId = 1
                        },
                        new
                        {
                            RequirementId = 62,
                            CriterionId = 21,
                            Description = "Incidenteel unit-test toegepast, echter niet voor alle code waarvoor dit zinvol zou zijn geweest.",
                            IndicatorId = 2
                        },
                        new
                        {
                            RequirementId = 63,
                            CriterionId = 21,
                            Description = "Voor alle code waarvoor dit zinvol is, zijn unit-testen toegepast.",
                            IndicatorId = 3
                        },
                        new
                        {
                            RequirementId = 64,
                            CriterionId = 22,
                            Description = "Niet alle namen beschrijven de intentie van de code correct.",
                            IndicatorId = 1
                        },
                        new
                        {
                            RequirementId = 65,
                            CriterionId = 22,
                            Description = "Alle namen in de code beschrijven de intentie van de code, maar niet altijd compleet en ook niet altijd even consistent.",
                            IndicatorId = 2
                        },
                        new
                        {
                            RequirementId = 66,
                            CriterionId = 22,
                            Description = "Alle namen in de code beschrijven de intentie van de code. Namen zijn compleet en consistent.",
                            IndicatorId = 3
                        },
                        new
                        {
                            RequirementId = 67,
                            CriterionId = 23,
                            Description = "Formattering mist of regels zijn te lang om te lezen.",
                            IndicatorId = 1
                        },
                        new
                        {
                            RequirementId = 68,
                            CriterionId = 23,
                            Description = "Inspringen , regelovergangen en het gebruik van haakjes gegeven een inzicht in de beoogde structuur.indentation, maar is niet consitent gedaan.",
                            IndicatorId = 2
                        },
                        new
                        {
                            RequirementId = 69,
                            CriterionId = 23,
                            Description = "Inspringen , regelovergangen en het gebruik van haakjes gegeven een perfect inzicht in de beoogde structuur.",
                            IndicatorId = 3
                        },
                        new
                        {
                            RequirementId = 70,
                            CriterionId = 24,
                            Description = "Methodes bevatten diep geneste code, controle structuren zijn misleidend voor de beoogde functionaliteit.",
                            IndicatorId = 1
                        },
                        new
                        {
                            RequirementId = 71,
                            CriterionId = 24,
                            Description = "De code is eenvoudig en bevat weinig exceptions. De controle structuren en keuzes voor libraries is toepasselijk voor de gewenste functionaliteit.",
                            IndicatorId = 2
                        },
                        new
                        {
                            RequirementId = 72,
                            CriterionId = 24,
                            Description = "De code is eenvoudig en bevat weinig exceptions. De controle structuren en keuzes voor libraries is toepasselijk voor de gewenste functionaliteit. De code laat het gewenste pad duidelijk tot uitdrukking komen.",
                            IndicatorId = 3
                        },
                        new
                        {
                            RequirementId = 73,
                            CriterionId = 25,
                            Description = "De code is geschreven in enkele grote klassen en methodes. Sommige code komt vaker voor (copy paste).",
                            IndicatorId = 1
                        },
                        new
                        {
                            RequirementId = 74,
                            CriterionId = 25,
                            Description = "De indeling in klassen en methodes maakt de code overzichtelijk, maar kan nog verder geoptimaliseerd worden. Dit blijkt bijvoorbeeld tijdens het schrijven van de unit testen.",
                            IndicatorId = 2
                        },
                        new
                        {
                            RequirementId = 75,
                            CriterionId = 25,
                            Description = "De indeling in klassen en methodes maakt de code overzichtelijk en goed testbaar. Methodes voeren een zeer beperkt aantal taken uit. ",
                            IndicatorId = 3
                        },
                        new
                        {
                            RequirementId = 76,
                            CriterionId = 26,
                            Description = "Er wordt een demo gegeven. Voor het publiek wordt niet expliciet  duidelijk gemaakt wat de items voor de sprint waren en wat daarvan al dan niet gerealiseerd is.",
                            IndicatorId = 1
                        },
                        new
                        {
                            RequirementId = 77,
                            CriterionId = 26,
                            Description = "Er wordt een demo gegeven en enigszins duidelijk gemaakt wat de te realiseren items waren en wat daarvan gerealiseerd is.",
                            IndicatorId = 2
                        },
                        new
                        {
                            RequirementId = 78,
                            CriterionId = 26,
                            Description = "Duidelijk overzicht van sprint items en hetgeen daarvan gerealiseerd is. Per item wordt een demo gegeven om aan te tonen dat het item gerealiseerd is.",
                            IndicatorId = 3
                        },
                        new
                        {
                            RequirementId = 79,
                            CriterionId = 27,
                            Description = "De burn down chart wordt niet getoond. De geplande velocity en de gerealiseerde velocity komen niet ter sprake.",
                            IndicatorId = 1
                        },
                        new
                        {
                            RequirementId = 80,
                            CriterionId = 27,
                            Description = "De burn down chart wordt getoond. De geplande en gerealiseerde velocity is duidelijk.",
                            IndicatorId = 2
                        },
                        new
                        {
                            RequirementId = 81,
                            CriterionId = 27,
                            Description = "De geplande velocity wordt vermeld. De burn down chart is correct, wordt getoond en uitgelegd. Het team trekt conclusies.",
                            IndicatorId = 3
                        },
                        new
                        {
                            RequirementId = 82,
                            CriterionId = 28,
                            Description = "Stand-ups worden niet dagelijks uitgevoerd.",
                            IndicatorId = 1
                        },
                        new
                        {
                            RequirementId = 83,
                            CriterionId = 28,
                            Description = "Stand-ups zijn dagelijks uitgevoerd. Bewijslast is mager.",
                            IndicatorId = 2
                        },
                        new
                        {
                            RequirementId = 84,
                            CriterionId = 28,
                            Description = "Stand-ups zijn dagelijks uitgevoerd. Bewijslast is geleverd. Uit de reflecties blijkt dat de studenten het nut van de stand-up goed doorgronden.",
                            IndicatorId = 3
                        },
                        new
                        {
                            RequirementId = 85,
                            CriterionId = 29,
                            Description = "Niet beschreven.",
                            IndicatorId = 1
                        },
                        new
                        {
                            RequirementId = 86,
                            CriterionId = 29,
                            Description = "De motivatie voor de keuze voor een bepaald tool is beschreven of de systematiek is beschreven en gemotiveerd, maar niet beide.",
                            IndicatorId = 2
                        },
                        new
                        {
                            RequirementId = 87,
                            CriterionId = 29,
                            Description = "De motivatie voor de keuze voor een bepaald tool is beschreven. Ook de systematiek is beschreven en gemotiveerd.",
                            IndicatorId = 3
                        },
                        new
                        {
                            RequirementId = 88,
                            CriterionId = 30,
                            Description = "Niet beschreven.",
                            IndicatorId = 1
                        },
                        new
                        {
                            RequirementId = 89,
                            CriterionId = 30,
                            Description = "De motivatie voor de keuze voor een bepaald tool is beschreven of de systematiek is beschreven en gemotiveerd, maar niet beide.",
                            IndicatorId = 2
                        },
                        new
                        {
                            RequirementId = 90,
                            CriterionId = 30,
                            Description = "De motivatie voor de keuze voor een bepaald tool is beschreven. Ook de systematiek is beschreven en gemotiveerd.",
                            IndicatorId = 3
                        },
                        new
                        {
                            RequirementId = 91,
                            CriterionId = 31,
                            Description = "Productbacklog items zijn beschreven, maar niet op een consistente wijze. Items zijn niet duidelijk beschreven.",
                            IndicatorId = 1
                        },
                        new
                        {
                            RequirementId = 92,
                            CriterionId = 31,
                            Description = "Productbacklog items zijn consistent beschreven, maar nog niet altijd in voldoende detail om de intentie goed te begrijpen.",
                            IndicatorId = 2
                        },
                        new
                        {
                            RequirementId = 93,
                            CriterionId = 31,
                            Description = "Productbacklog items zijn in voldoende detail en consistent beschreven in de product backlog. De intentie is voor alle betrokkenen goed te begrijpen.",
                            IndicatorId = 3
                        },
                        new
                        {
                            RequirementId = 94,
                            CriterionId = 32,
                            Description = "Er is geen verschil te onderkennen in detaillering.",
                            IndicatorId = 1
                        },
                        new
                        {
                            RequirementId = 95,
                            CriterionId = 32,
                            Description = "Soms zijn items met een hoge prioriteit al verder in detail uitgewerkt. Dit gebeurt echter nog niet structureel.",
                            IndicatorId = 2
                        },
                        new
                        {
                            RequirementId = 96,
                            CriterionId = 32,
                            Description = "Productbacklog items met een hoge prioriteit zijn al duidelijk verder uitgewerkt in vergelijking met items met een lage prioriteit. Dit heeft continue de aandacht van het team.",
                            IndicatorId = 3
                        },
                        new
                        {
                            RequirementId = 97,
                            CriterionId = 33,
                            Description = "Afstemming vind buiten de sprint planning meetings niet plaats. Zelfs tijdens de meetings komt dit nauwelijks aan bod. Soms weet de product owner of teamleden niet wat de bedoeling van een item is of wordt deze verschillend geïnterpreteerd",
                            IndicatorId = 1
                        },
                        new
                        {
                            RequirementId = 98,
                            CriterionId = 33,
                            Description = "Afstemming vind plaats, bijvoorbeeld door na afloop van een meeting een overzicht aan de product owner te versturen. Echte afstemming vind echter niet plaats. Soms interpreteert de product owner een item nog anders dan het team.",
                            IndicatorId = 2
                        },
                        new
                        {
                            RequirementId = 99,
                            CriterionId = 33,
                            Description = "Zowel de product owner als de teamleden weten precies te vertellen wat een item inhoudt. Afstemming van items vind ook buiten de meetings om plaats.",
                            IndicatorId = 3
                        },
                        new
                        {
                            RequirementId = 100,
                            CriterionId = 34,
                            Description = "Bugs worden niet geadministreerd.",
                            IndicatorId = 1
                        },
                        new
                        {
                            RequirementId = 101,
                            CriterionId = 34,
                            Description = "Bugs worden geadministreert, maar het oplossen hiervan heeft niet een duidelijk plaats gekregen in het software ontwikkelproces.",
                            IndicatorId = 2
                        },
                        new
                        {
                            RequirementId = 102,
                            CriterionId = 34,
                            Description = "Bekende bugs worden geadminstreerd (bijvoorbeeld door ze op te nemen in de product backlog) en het oplossen hiervan heeft een plaats gekregen in het software ontwikkelproces. De product owner bepaald de prioriteit van het oplossen van de bugs. Er kan prioriteit gegeven worden aan het toevoegen van nieuwe functionaliteit, boven het oplossen van een bug.",
                            IndicatorId = 3
                        },
                        new
                        {
                            RequirementId = 103,
                            CriterionId = 35,
                            Description = "De retrospective is niet uitgevoerd.",
                            IndicatorId = 1
                        },
                        new
                        {
                            RequirementId = 104,
                            CriterionId = 35,
                            Description = "De retrospective is na afloop van de laatste twee sprints uitgevoerd en heeft (indien nodig) geleid tot aanpassingen op het proces.",
                            IndicatorId = 2
                        },
                        new
                        {
                            RequirementId = 105,
                            CriterionId = 35,
                            Description = "De retrospective is van het begin af aan uitgevoerd en heeft (indien nodig) geleid tot aanpassingen op het proces.",
                            IndicatorId = 3
                        },
                        new
                        {
                            RequirementId = 106,
                            CriterionId = 36,
                            Description = "Er is geen definition of done.",
                            IndicatorId = 1
                        },
                        new
                        {
                            RequirementId = 107,
                            CriterionId = 36,
                            Description = "Er is een standaard definition of done.",
                            IndicatorId = 2
                        },
                        new
                        {
                            RequirementId = 108,
                            CriterionId = 36,
                            Description = "Feedback (bijvoorbeeld verkregen tijdens een retrospective)  is verwerkt in een aangepast definition of done.",
                            IndicatorId = 3
                        },
                        new
                        {
                            RequirementId = 109,
                            CriterionId = 37,
                            Description = "Definition of done wordt niet gevolgd.",
                            IndicatorId = 1
                        },
                        new
                        {
                            RequirementId = 110,
                            CriterionId = 37,
                            Description = "De definition of done wordt strict gevolgt. Tijdens de eerste sprint is dit nog niet helemaal gelukt",
                            IndicatorId = 2
                        },
                        new
                        {
                            RequirementId = 111,
                            CriterionId = 37,
                            Description = "De definition of done wordt van het begin af aan strict gevolgd.",
                            IndicatorId = 3
                        },
                        new
                        {
                            RequirementId = 112,
                            CriterionId = 38,
                            Description = "De student gaat hier niet op in.",
                            IndicatorId = 1
                        },
                        new
                        {
                            RequirementId = 113,
                            CriterionId = 38,
                            Description = "De student reflecteert op de verbeteringen.",
                            IndicatorId = 2
                        },
                        new
                        {
                            RequirementId = 114,
                            CriterionId = 38,
                            Description = "De student reflecteert op de verbeteringen en geeft duidelijk aan wat zijn of haar rol hierin is geweest.",
                            IndicatorId = 3
                        },
                        new
                        {
                            RequirementId = 115,
                            CriterionId = 39,
                            Description = "De student is zijn leerdoelen uit het oog verloren.",
                            IndicatorId = 1
                        },
                        new
                        {
                            RequirementId = 116,
                            CriterionId = 39,
                            Description = "De student is actief met de leerdoelen aan de slag gegaan. ",
                            IndicatorId = 2
                        },
                        new
                        {
                            RequirementId = 117,
                            CriterionId = 39,
                            Description = "De student is actief met de leerdoelen aan de slag gegaan en reflecteerd hier uitgebreid op.",
                            IndicatorId = 3
                        },
                        new
                        {
                            RequirementId = 118,
                            CriterionId = 40,
                            Description = "De student besteed hier geen aandacht aan.",
                            IndicatorId = 1
                        },
                        new
                        {
                            RequirementId = 119,
                            CriterionId = 40,
                            Description = "De student beschrijft zijn professionele ontwikkeling.",
                            IndicatorId = 2
                        },
                        new
                        {
                            RequirementId = 120,
                            CriterionId = 40,
                            Description = "De student beschrijft zijn professionele ontwikkeling. Uit de reflectie blijkt dat de student een project aangrijpt om voor zichzelf stappen te maken op het vlak van persoonlijke ontwikkeling.",
                            IndicatorId = 3
                        },
                        new
                        {
                            RequirementId = 121,
                            CriterionId = 41,
                            Description = "De student besteed hier geen aandacht aan.",
                            IndicatorId = 1
                        },
                        new
                        {
                            RequirementId = 122,
                            CriterionId = 41,
                            Description = "De student is zich bewust van zijn eigen sterktes en zwaktes en beschrijft deze in de reflectie.",
                            IndicatorId = 2
                        },
                        new
                        {
                            RequirementId = 123,
                            CriterionId = 41,
                            Description = "De student is zich bewust van zijn eigen sterktes en zwaktes en beschrijft deze in de reflectie. De student geeft duidelijk aan hoe hij of zij in de toekomst de sterktes optimaal kan inzetten, en hoe hij of zij de zwaktes gaat opvangen en/of zich op deze punten gaat verbeteren.",
                            IndicatorId = 3
                        },
                        new
                        {
                            RequirementId = 124,
                            CriterionId = 42,
                            Description = "Er wordt hoofdzakelijk beschreven wat er is opgeleverd.",
                            IndicatorId = 1
                        },
                        new
                        {
                            RequirementId = 125,
                            CriterionId = 42,
                            Description = "Er wordt beschreven wat er is opgeleverd en wat de bijdrage is geweest van iedere student. Op gemaakte keuzes wordt gereflecteerd. Studenten laten zien dat ze weten wat hun ontwikkelpunten nog zijn. Diepgang en bewijsmateriaal is mager.",
                            IndicatorId = 2
                        },
                        new
                        {
                            RequirementId = 126,
                            CriterionId = 42,
                            Description = "Er wordt een gedetailleerde reflectie opgeleverd, compleet met bewijsmateriaal (zoals bijv. foto’s van meetings met gevuld white board). Op gemaakte keuzes wordt gereflecteerd. Studenten laten zien dat ze weten wat hun ontwikkelpunten nog zijn. De studenten nemen hun eigen handelen kritisch onder de loep. Een docent die niet bij het project betrokken is geweest, kan op basis van de reflectie een gefundeerde, individuele beoordeling geven.",
                            IndicatorId = 3
                        });
                });

            modelBuilder.Entity("Model.Student", b =>
                {
                    b.Property<int>("StudentNumber")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentNumber");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Model.Assessment", b =>
                {
                    b.HasOne("Model.Group", "Group")
                        .WithMany("Assessments")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Project", "Project")
                        .WithMany("Assessments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Model.Competence", b =>
                {
                    b.HasOne("Model.Form", "Form")
                        .WithMany("Competences")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Form");
                });

            modelBuilder.Entity("Model.Criterion", b =>
                {
                    b.HasOne("Model.Competence", "Competence")
                        .WithMany("Criteria")
                        .HasForeignKey("CompetenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competence");
                });

            modelBuilder.Entity("Model.FormIndicator", b =>
                {
                    b.HasOne("Model.Form", "Form")
                        .WithMany("FromIndicators")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Indicator", "Indicator")
                        .WithMany("FromIndicators")
                        .HasForeignKey("IndicatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Form");

                    b.Navigation("Indicator");
                });

            modelBuilder.Entity("Model.GroupStudent", b =>
                {
                    b.HasOne("Model.Group", "Group")
                        .WithMany("GroupStudents")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Student", "Student")
                        .WithMany("GroupStudents")
                        .HasForeignKey("StudentNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Model.Project", b =>
                {
                    b.HasOne("Model.Form", "Form")
                        .WithMany("Projects")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Form");
                });

            modelBuilder.Entity("Model.Rating", b =>
                {
                    b.HasOne("Model.Assessment", "Assessment")
                        .WithMany("Ratings")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Criterion", "Criterion")
                        .WithMany("Ratings")
                        .HasForeignKey("CriterionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Model.Requirement", "Requirement")
                        .WithMany("Ratings")
                        .HasForeignKey("RequirementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assessment");

                    b.Navigation("Criterion");

                    b.Navigation("Requirement");
                });

            modelBuilder.Entity("Model.Requirement", b =>
                {
                    b.HasOne("Model.Criterion", "Criterion")
                        .WithMany("Requirements")
                        .HasForeignKey("CriterionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Indicator", "Indicator")
                        .WithMany()
                        .HasForeignKey("IndicatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Criterion");

                    b.Navigation("Indicator");
                });

            modelBuilder.Entity("Model.Assessment", b =>
                {
                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("Model.Competence", b =>
                {
                    b.Navigation("Criteria");
                });

            modelBuilder.Entity("Model.Criterion", b =>
                {
                    b.Navigation("Ratings");

                    b.Navigation("Requirements");
                });

            modelBuilder.Entity("Model.Form", b =>
                {
                    b.Navigation("Competences");

                    b.Navigation("FromIndicators");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Model.Group", b =>
                {
                    b.Navigation("Assessments");

                    b.Navigation("GroupStudents");
                });

            modelBuilder.Entity("Model.Indicator", b =>
                {
                    b.Navigation("FromIndicators");
                });

            modelBuilder.Entity("Model.Project", b =>
                {
                    b.Navigation("Assessments");
                });

            modelBuilder.Entity("Model.Requirement", b =>
                {
                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("Model.Student", b =>
                {
                    b.Navigation("GroupStudents");
                });
#pragma warning restore 612, 618
        }
    }
}
