// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Service.Database;

#nullable disable

namespace Service.Database.Migrations
{
    [DbContext(typeof(AssessmentContext))]
    [Migration("20220520081544_DebugSeed")]
    partial class DebugSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Model.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupId"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("GroupId");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            GroupId = 1,
                            Name = "Bode LLC",
                            Number = 3
                        },
                        new
                        {
                            GroupId = 2,
                            Name = "Mraz, Kozey and Ebert",
                            Number = 2
                        },
                        new
                        {
                            GroupId = 3,
                            Name = "Kunze - Swift",
                            Number = 3
                        },
                        new
                        {
                            GroupId = 4,
                            Name = "Cruickshank, Wintheiser and Hills",
                            Number = 6
                        },
                        new
                        {
                            GroupId = 5,
                            Name = "Gutkowski Group",
                            Number = 2
                        },
                        new
                        {
                            GroupId = 6,
                            Name = "Kohler - Kessler",
                            Number = 1
                        },
                        new
                        {
                            GroupId = 7,
                            Name = "McDermott - Bode",
                            Number = 6
                        },
                        new
                        {
                            GroupId = 8,
                            Name = "Kerluke, Stanton and Mayert",
                            Number = 5
                        },
                        new
                        {
                            GroupId = 9,
                            Name = "Kemmer Group",
                            Number = 3
                        },
                        new
                        {
                            GroupId = 10,
                            Name = "Jacobi Group",
                            Number = 4
                        },
                        new
                        {
                            GroupId = 11,
                            Name = "MacGyver - Russel",
                            Number = 2
                        },
                        new
                        {
                            GroupId = 12,
                            Name = "Johnston and Sons",
                            Number = 3
                        },
                        new
                        {
                            GroupId = 13,
                            Name = "Luettgen - Howe",
                            Number = 4
                        },
                        new
                        {
                            GroupId = 14,
                            Name = "Krajcik, Bashirian and Corwin",
                            Number = 4
                        },
                        new
                        {
                            GroupId = 15,
                            Name = "Quitzon, Thiel and Trantow",
                            Number = 4
                        },
                        new
                        {
                            GroupId = 16,
                            Name = "Goldner and Sons",
                            Number = 2
                        },
                        new
                        {
                            GroupId = 17,
                            Name = "Barrows, Zulauf and Donnelly",
                            Number = 6
                        },
                        new
                        {
                            GroupId = 18,
                            Name = "Pfannerstill - Jenkins",
                            Number = 1
                        },
                        new
                        {
                            GroupId = 19,
                            Name = "Russel, Ortiz and Schimmel",
                            Number = 5
                        },
                        new
                        {
                            GroupId = 20,
                            Name = "Jacobi, West and Schimmel",
                            Number = 5
                        },
                        new
                        {
                            GroupId = 21,
                            Name = "Smitham Group",
                            Number = 5
                        },
                        new
                        {
                            GroupId = 22,
                            Name = "Mante, Prohaska and Klein",
                            Number = 5
                        },
                        new
                        {
                            GroupId = 23,
                            Name = "Ruecker - Gerlach",
                            Number = 2
                        },
                        new
                        {
                            GroupId = 24,
                            Name = "Skiles - Marks",
                            Number = 2
                        },
                        new
                        {
                            GroupId = 25,
                            Name = "O'Conner, Kassulke and Gorczany",
                            Number = 6
                        },
                        new
                        {
                            GroupId = 26,
                            Name = "Franecki - Little",
                            Number = 2
                        },
                        new
                        {
                            GroupId = 27,
                            Name = "Hoeger, Murray and Bradtke",
                            Number = 4
                        },
                        new
                        {
                            GroupId = 28,
                            Name = "Morissette and Sons",
                            Number = 1
                        },
                        new
                        {
                            GroupId = 29,
                            Name = "Nader - Weissnat",
                            Number = 4
                        },
                        new
                        {
                            GroupId = 30,
                            Name = "Cummings - Langosh",
                            Number = 5
                        },
                        new
                        {
                            GroupId = 31,
                            Name = "Toy LLC",
                            Number = 2
                        },
                        new
                        {
                            GroupId = 32,
                            Name = "Roberts and Sons",
                            Number = 4
                        },
                        new
                        {
                            GroupId = 33,
                            Name = "Jacobson Group",
                            Number = 5
                        },
                        new
                        {
                            GroupId = 34,
                            Name = "Wiegand, Goldner and Hettinger",
                            Number = 5
                        },
                        new
                        {
                            GroupId = 35,
                            Name = "Kiehn - Schulist",
                            Number = 6
                        },
                        new
                        {
                            GroupId = 36,
                            Name = "Keeling, Reichel and Lebsack",
                            Number = 5
                        });
                });

            modelBuilder.Entity("Model.GroupStudent", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("StudentNumber")
                        .HasColumnType("int");

                    b.HasKey("GroupId", "StudentNumber");

                    b.HasIndex("StudentNumber");

                    b.ToTable("GroupStudent");

                    b.HasData(
                        new
                        {
                            GroupId = 1,
                            StudentNumber = 115192
                        },
                        new
                        {
                            GroupId = 1,
                            StudentNumber = 115439
                        },
                        new
                        {
                            GroupId = 1,
                            StudentNumber = 115083
                        },
                        new
                        {
                            GroupId = 1,
                            StudentNumber = 115459
                        },
                        new
                        {
                            GroupId = 1,
                            StudentNumber = 115237
                        },
                        new
                        {
                            GroupId = 1,
                            StudentNumber = 115352
                        },
                        new
                        {
                            GroupId = 1,
                            StudentNumber = 115460
                        },
                        new
                        {
                            GroupId = 1,
                            StudentNumber = 115018
                        },
                        new
                        {
                            GroupId = 2,
                            StudentNumber = 115358
                        },
                        new
                        {
                            GroupId = 2,
                            StudentNumber = 115222
                        },
                        new
                        {
                            GroupId = 3,
                            StudentNumber = 115527
                        },
                        new
                        {
                            GroupId = 3,
                            StudentNumber = 115265
                        },
                        new
                        {
                            GroupId = 3,
                            StudentNumber = 115449
                        },
                        new
                        {
                            GroupId = 4,
                            StudentNumber = 115460
                        },
                        new
                        {
                            GroupId = 4,
                            StudentNumber = 115426
                        },
                        new
                        {
                            GroupId = 4,
                            StudentNumber = 115494
                        },
                        new
                        {
                            GroupId = 4,
                            StudentNumber = 115344
                        },
                        new
                        {
                            GroupId = 4,
                            StudentNumber = 115129
                        },
                        new
                        {
                            GroupId = 4,
                            StudentNumber = 115471
                        },
                        new
                        {
                            GroupId = 4,
                            StudentNumber = 115205
                        },
                        new
                        {
                            GroupId = 5,
                            StudentNumber = 115134
                        },
                        new
                        {
                            GroupId = 5,
                            StudentNumber = 115080
                        },
                        new
                        {
                            GroupId = 5,
                            StudentNumber = 115194
                        },
                        new
                        {
                            GroupId = 6,
                            StudentNumber = 115194
                        },
                        new
                        {
                            GroupId = 6,
                            StudentNumber = 115460
                        },
                        new
                        {
                            GroupId = 6,
                            StudentNumber = 115139
                        },
                        new
                        {
                            GroupId = 6,
                            StudentNumber = 115212
                        },
                        new
                        {
                            GroupId = 7,
                            StudentNumber = 115350
                        },
                        new
                        {
                            GroupId = 7,
                            StudentNumber = 115494
                        },
                        new
                        {
                            GroupId = 8,
                            StudentNumber = 115503
                        },
                        new
                        {
                            GroupId = 8,
                            StudentNumber = 115205
                        },
                        new
                        {
                            GroupId = 8,
                            StudentNumber = 115143
                        },
                        new
                        {
                            GroupId = 8,
                            StudentNumber = 115233
                        },
                        new
                        {
                            GroupId = 8,
                            StudentNumber = 115122
                        },
                        new
                        {
                            GroupId = 8,
                            StudentNumber = 115129
                        },
                        new
                        {
                            GroupId = 8,
                            StudentNumber = 115515
                        },
                        new
                        {
                            GroupId = 8,
                            StudentNumber = 115482
                        },
                        new
                        {
                            GroupId = 9,
                            StudentNumber = 115112
                        },
                        new
                        {
                            GroupId = 9,
                            StudentNumber = 115476
                        },
                        new
                        {
                            GroupId = 9,
                            StudentNumber = 115103
                        },
                        new
                        {
                            GroupId = 10,
                            StudentNumber = 115468
                        },
                        new
                        {
                            GroupId = 10,
                            StudentNumber = 115200
                        },
                        new
                        {
                            GroupId = 11,
                            StudentNumber = 115194
                        },
                        new
                        {
                            GroupId = 11,
                            StudentNumber = 115459
                        },
                        new
                        {
                            GroupId = 11,
                            StudentNumber = 115070
                        },
                        new
                        {
                            GroupId = 11,
                            StudentNumber = 115108
                        },
                        new
                        {
                            GroupId = 11,
                            StudentNumber = 115122
                        },
                        new
                        {
                            GroupId = 12,
                            StudentNumber = 115080
                        },
                        new
                        {
                            GroupId = 12,
                            StudentNumber = 115255
                        },
                        new
                        {
                            GroupId = 12,
                            StudentNumber = 115527
                        },
                        new
                        {
                            GroupId = 12,
                            StudentNumber = 115491
                        },
                        new
                        {
                            GroupId = 12,
                            StudentNumber = 115449
                        },
                        new
                        {
                            GroupId = 12,
                            StudentNumber = 115265
                        },
                        new
                        {
                            GroupId = 12,
                            StudentNumber = 115112
                        },
                        new
                        {
                            GroupId = 13,
                            StudentNumber = 115154
                        },
                        new
                        {
                            GroupId = 13,
                            StudentNumber = 115080
                        },
                        new
                        {
                            GroupId = 13,
                            StudentNumber = 115275
                        },
                        new
                        {
                            GroupId = 13,
                            StudentNumber = 115449
                        },
                        new
                        {
                            GroupId = 13,
                            StudentNumber = 115288
                        },
                        new
                        {
                            GroupId = 14,
                            StudentNumber = 115501
                        },
                        new
                        {
                            GroupId = 14,
                            StudentNumber = 115292
                        },
                        new
                        {
                            GroupId = 14,
                            StudentNumber = 115382
                        },
                        new
                        {
                            GroupId = 15,
                            StudentNumber = 115068
                        },
                        new
                        {
                            GroupId = 15,
                            StudentNumber = 115055
                        },
                        new
                        {
                            GroupId = 15,
                            StudentNumber = 115083
                        },
                        new
                        {
                            GroupId = 15,
                            StudentNumber = 115103
                        },
                        new
                        {
                            GroupId = 15,
                            StudentNumber = 115233
                        },
                        new
                        {
                            GroupId = 16,
                            StudentNumber = 115143
                        },
                        new
                        {
                            GroupId = 16,
                            StudentNumber = 115275
                        },
                        new
                        {
                            GroupId = 16,
                            StudentNumber = 115134
                        },
                        new
                        {
                            GroupId = 17,
                            StudentNumber = 115523
                        },
                        new
                        {
                            GroupId = 17,
                            StudentNumber = 115366
                        },
                        new
                        {
                            GroupId = 17,
                            StudentNumber = 115143
                        },
                        new
                        {
                            GroupId = 17,
                            StudentNumber = 115484
                        },
                        new
                        {
                            GroupId = 17,
                            StudentNumber = 115363
                        },
                        new
                        {
                            GroupId = 17,
                            StudentNumber = 115261
                        },
                        new
                        {
                            GroupId = 17,
                            StudentNumber = 115339
                        },
                        new
                        {
                            GroupId = 17,
                            StudentNumber = 115237
                        },
                        new
                        {
                            GroupId = 18,
                            StudentNumber = 115527
                        },
                        new
                        {
                            GroupId = 18,
                            StudentNumber = 115143
                        },
                        new
                        {
                            GroupId = 18,
                            StudentNumber = 115218
                        },
                        new
                        {
                            GroupId = 18,
                            StudentNumber = 115350
                        },
                        new
                        {
                            GroupId = 18,
                            StudentNumber = 115410
                        },
                        new
                        {
                            GroupId = 18,
                            StudentNumber = 115449
                        },
                        new
                        {
                            GroupId = 19,
                            StudentNumber = 115233
                        },
                        new
                        {
                            GroupId = 19,
                            StudentNumber = 115103
                        },
                        new
                        {
                            GroupId = 19,
                            StudentNumber = 115261
                        },
                        new
                        {
                            GroupId = 19,
                            StudentNumber = 115517
                        },
                        new
                        {
                            GroupId = 19,
                            StudentNumber = 115413
                        },
                        new
                        {
                            GroupId = 19,
                            StudentNumber = 115518
                        },
                        new
                        {
                            GroupId = 19,
                            StudentNumber = 115302
                        },
                        new
                        {
                            GroupId = 19,
                            StudentNumber = 115523
                        },
                        new
                        {
                            GroupId = 20,
                            StudentNumber = 115237
                        },
                        new
                        {
                            GroupId = 20,
                            StudentNumber = 115433
                        },
                        new
                        {
                            GroupId = 21,
                            StudentNumber = 115259
                        },
                        new
                        {
                            GroupId = 21,
                            StudentNumber = 115312
                        },
                        new
                        {
                            GroupId = 22,
                            StudentNumber = 115447
                        },
                        new
                        {
                            GroupId = 22,
                            StudentNumber = 115489
                        },
                        new
                        {
                            GroupId = 23,
                            StudentNumber = 115255
                        },
                        new
                        {
                            GroupId = 23,
                            StudentNumber = 115454
                        },
                        new
                        {
                            GroupId = 23,
                            StudentNumber = 115503
                        },
                        new
                        {
                            GroupId = 23,
                            StudentNumber = 115192
                        },
                        new
                        {
                            GroupId = 24,
                            StudentNumber = 115488
                        },
                        new
                        {
                            GroupId = 24,
                            StudentNumber = 115178
                        },
                        new
                        {
                            GroupId = 24,
                            StudentNumber = 115212
                        },
                        new
                        {
                            GroupId = 24,
                            StudentNumber = 115517
                        },
                        new
                        {
                            GroupId = 24,
                            StudentNumber = 115080
                        },
                        new
                        {
                            GroupId = 24,
                            StudentNumber = 115512
                        },
                        new
                        {
                            GroupId = 24,
                            StudentNumber = 115339
                        },
                        new
                        {
                            GroupId = 24,
                            StudentNumber = 115370
                        },
                        new
                        {
                            GroupId = 25,
                            StudentNumber = 115108
                        },
                        new
                        {
                            GroupId = 25,
                            StudentNumber = 115358
                        },
                        new
                        {
                            GroupId = 25,
                            StudentNumber = 115101
                        },
                        new
                        {
                            GroupId = 25,
                            StudentNumber = 115501
                        },
                        new
                        {
                            GroupId = 25,
                            StudentNumber = 115069
                        },
                        new
                        {
                            GroupId = 25,
                            StudentNumber = 115142
                        },
                        new
                        {
                            GroupId = 25,
                            StudentNumber = 115118
                        },
                        new
                        {
                            GroupId = 26,
                            StudentNumber = 115112
                        },
                        new
                        {
                            GroupId = 26,
                            StudentNumber = 115100
                        },
                        new
                        {
                            GroupId = 26,
                            StudentNumber = 115091
                        },
                        new
                        {
                            GroupId = 26,
                            StudentNumber = 115052
                        },
                        new
                        {
                            GroupId = 26,
                            StudentNumber = 115081
                        },
                        new
                        {
                            GroupId = 27,
                            StudentNumber = 115370
                        },
                        new
                        {
                            GroupId = 27,
                            StudentNumber = 115052
                        },
                        new
                        {
                            GroupId = 27,
                            StudentNumber = 115129
                        },
                        new
                        {
                            GroupId = 27,
                            StudentNumber = 115255
                        },
                        new
                        {
                            GroupId = 28,
                            StudentNumber = 115460
                        },
                        new
                        {
                            GroupId = 28,
                            StudentNumber = 115127
                        },
                        new
                        {
                            GroupId = 28,
                            StudentNumber = 115444
                        },
                        new
                        {
                            GroupId = 28,
                            StudentNumber = 115213
                        },
                        new
                        {
                            GroupId = 28,
                            StudentNumber = 115512
                        },
                        new
                        {
                            GroupId = 29,
                            StudentNumber = 115079
                        },
                        new
                        {
                            GroupId = 29,
                            StudentNumber = 115459
                        },
                        new
                        {
                            GroupId = 29,
                            StudentNumber = 115339
                        },
                        new
                        {
                            GroupId = 29,
                            StudentNumber = 115178
                        },
                        new
                        {
                            GroupId = 29,
                            StudentNumber = 115112
                        },
                        new
                        {
                            GroupId = 30,
                            StudentNumber = 115484
                        },
                        new
                        {
                            GroupId = 30,
                            StudentNumber = 115080
                        },
                        new
                        {
                            GroupId = 31,
                            StudentNumber = 115100
                        },
                        new
                        {
                            GroupId = 31,
                            StudentNumber = 115143
                        },
                        new
                        {
                            GroupId = 31,
                            StudentNumber = 115108
                        },
                        new
                        {
                            GroupId = 31,
                            StudentNumber = 115471
                        },
                        new
                        {
                            GroupId = 32,
                            StudentNumber = 115139
                        },
                        new
                        {
                            GroupId = 32,
                            StudentNumber = 115483
                        },
                        new
                        {
                            GroupId = 32,
                            StudentNumber = 115506
                        },
                        new
                        {
                            GroupId = 32,
                            StudentNumber = 115194
                        },
                        new
                        {
                            GroupId = 32,
                            StudentNumber = 115468
                        },
                        new
                        {
                            GroupId = 33,
                            StudentNumber = 115464
                        },
                        new
                        {
                            GroupId = 33,
                            StudentNumber = 115426
                        },
                        new
                        {
                            GroupId = 33,
                            StudentNumber = 115143
                        },
                        new
                        {
                            GroupId = 33,
                            StudentNumber = 115139
                        },
                        new
                        {
                            GroupId = 34,
                            StudentNumber = 115255
                        },
                        new
                        {
                            GroupId = 34,
                            StudentNumber = 115052
                        },
                        new
                        {
                            GroupId = 35,
                            StudentNumber = 115410
                        },
                        new
                        {
                            GroupId = 35,
                            StudentNumber = 115170
                        },
                        new
                        {
                            GroupId = 35,
                            StudentNumber = 115201
                        },
                        new
                        {
                            GroupId = 35,
                            StudentNumber = 115506
                        },
                        new
                        {
                            GroupId = 35,
                            StudentNumber = 115261
                        },
                        new
                        {
                            GroupId = 35,
                            StudentNumber = 115192
                        },
                        new
                        {
                            GroupId = 35,
                            StudentNumber = 115260
                        },
                        new
                        {
                            GroupId = 35,
                            StudentNumber = 115148
                        },
                        new
                        {
                            GroupId = 36,
                            StudentNumber = 115091
                        },
                        new
                        {
                            GroupId = 36,
                            StudentNumber = 115288
                        });
                });

            modelBuilder.Entity("Model.Indicator", b =>
                {
                    b.Property<int>("IndicatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IndicatorId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("IndicatorId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Indicators");

                    b.HasData(
                        new
                        {
                            IndicatorId = 1,
                            Name = "Lead",
                            Value = 4
                        },
                        new
                        {
                            IndicatorId = 2,
                            Name = "HTTP",
                            Value = 4
                        },
                        new
                        {
                            IndicatorId = 3,
                            Name = "National",
                            Value = 10
                        },
                        new
                        {
                            IndicatorId = 4,
                            Name = "Awesome Steel Chair",
                            Value = 9
                        },
                        new
                        {
                            IndicatorId = 5,
                            Name = "Fantastic Granite Pants",
                            Value = 2
                        },
                        new
                        {
                            IndicatorId = 6,
                            Name = "Borders",
                            Value = 2
                        },
                        new
                        {
                            IndicatorId = 7,
                            Name = "Stravenue",
                            Value = 3
                        },
                        new
                        {
                            IndicatorId = 8,
                            Name = "Unbranded Granite Bike",
                            Value = 6
                        },
                        new
                        {
                            IndicatorId = 9,
                            Name = "maximize",
                            Value = 4
                        });
                });

            modelBuilder.Entity("Model.Student", b =>
                {
                    b.Property<int>("StudentNumber")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentNumber");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentNumber = 115178,
                            Name = "Cletus Nolan"
                        },
                        new
                        {
                            StudentNumber = 115129,
                            Name = "Alivia Gutkowski"
                        },
                        new
                        {
                            StudentNumber = 115413,
                            Name = "Ewald Bosco"
                        },
                        new
                        {
                            StudentNumber = 115189,
                            Name = "Rickey Watsica"
                        },
                        new
                        {
                            StudentNumber = 115265,
                            Name = "Katelynn Welch"
                        },
                        new
                        {
                            StudentNumber = 115222,
                            Name = "Destini Mueller"
                        },
                        new
                        {
                            StudentNumber = 115193,
                            Name = "Danielle Nitzsche"
                        },
                        new
                        {
                            StudentNumber = 115266,
                            Name = "Juliana Hane"
                        },
                        new
                        {
                            StudentNumber = 115218,
                            Name = "Cristian Rosenbaum"
                        },
                        new
                        {
                            StudentNumber = 115237,
                            Name = "Breanne Miller"
                        },
                        new
                        {
                            StudentNumber = 115100,
                            Name = "Carmelo Reynolds"
                        },
                        new
                        {
                            StudentNumber = 115454,
                            Name = "Luigi Rogahn"
                        },
                        new
                        {
                            StudentNumber = 115068,
                            Name = "Rosemarie Pfeffer"
                        },
                        new
                        {
                            StudentNumber = 115419,
                            Name = "Maritza White"
                        },
                        new
                        {
                            StudentNumber = 115192,
                            Name = "Elmira Ratke"
                        },
                        new
                        {
                            StudentNumber = 115482,
                            Name = "Rowan Rippin"
                        },
                        new
                        {
                            StudentNumber = 115352,
                            Name = "Damien Zieme"
                        },
                        new
                        {
                            StudentNumber = 115489,
                            Name = "Emanuel Hand"
                        },
                        new
                        {
                            StudentNumber = 115070,
                            Name = "Otis Kohler"
                        },
                        new
                        {
                            StudentNumber = 115483,
                            Name = "Madie Armstrong"
                        },
                        new
                        {
                            StudentNumber = 115488,
                            Name = "Judge Stroman"
                        },
                        new
                        {
                            StudentNumber = 115127,
                            Name = "Webster Lueilwitz"
                        },
                        new
                        {
                            StudentNumber = 115134,
                            Name = "Dimitri Stamm"
                        },
                        new
                        {
                            StudentNumber = 115080,
                            Name = "Lavonne Buckridge"
                        },
                        new
                        {
                            StudentNumber = 115018,
                            Name = "Elsa Schinner"
                        },
                        new
                        {
                            StudentNumber = 115363,
                            Name = "Selmer Grady"
                        },
                        new
                        {
                            StudentNumber = 115512,
                            Name = "Howell Legros"
                        },
                        new
                        {
                            StudentNumber = 115476,
                            Name = "Alfonso Schaden"
                        },
                        new
                        {
                            StudentNumber = 115122,
                            Name = "Stella Erdman"
                        },
                        new
                        {
                            StudentNumber = 115205,
                            Name = "Zita Beatty"
                        },
                        new
                        {
                            StudentNumber = 115142,
                            Name = "Hiram Turcotte"
                        },
                        new
                        {
                            StudentNumber = 115460,
                            Name = "Humberto O'Keefe"
                        },
                        new
                        {
                            StudentNumber = 115523,
                            Name = "Kody Hagenes"
                        },
                        new
                        {
                            StudentNumber = 115163,
                            Name = "Oceane Adams"
                        },
                        new
                        {
                            StudentNumber = 115350,
                            Name = "Royce Ledner"
                        },
                        new
                        {
                            StudentNumber = 115447,
                            Name = "Ila Hudson"
                        },
                        new
                        {
                            StudentNumber = 115259,
                            Name = "Jammie Nikolaus"
                        },
                        new
                        {
                            StudentNumber = 115484,
                            Name = "Emmie Pollich"
                        },
                        new
                        {
                            StudentNumber = 115426,
                            Name = "Kassandra Volkman"
                        },
                        new
                        {
                            StudentNumber = 115101,
                            Name = "Vanessa Klocko"
                        },
                        new
                        {
                            StudentNumber = 115037,
                            Name = "Reggie Kris"
                        },
                        new
                        {
                            StudentNumber = 115517,
                            Name = "Drake Breitenberg"
                        },
                        new
                        {
                            StudentNumber = 115358,
                            Name = "Leonie Nader"
                        },
                        new
                        {
                            StudentNumber = 115275,
                            Name = "Karolann Jacobi"
                        },
                        new
                        {
                            StudentNumber = 115328,
                            Name = "Tyson Haley"
                        },
                        new
                        {
                            StudentNumber = 115118,
                            Name = "Taurean Hudson"
                        },
                        new
                        {
                            StudentNumber = 115012,
                            Name = "Evangeline Hansen"
                        },
                        new
                        {
                            StudentNumber = 115148,
                            Name = "Eva Block"
                        },
                        new
                        {
                            StudentNumber = 115108,
                            Name = "Curt Herman"
                        },
                        new
                        {
                            StudentNumber = 115213,
                            Name = "Verda Daniel"
                        },
                        new
                        {
                            StudentNumber = 115170,
                            Name = "Carolanne Runte"
                        },
                        new
                        {
                            StudentNumber = 115112,
                            Name = "Anita Hagenes"
                        },
                        new
                        {
                            StudentNumber = 115439,
                            Name = "Sincere Doyle"
                        },
                        new
                        {
                            StudentNumber = 115083,
                            Name = "Clifford Senger"
                        },
                        new
                        {
                            StudentNumber = 115491,
                            Name = "Raymond Shanahan"
                        },
                        new
                        {
                            StudentNumber = 115515,
                            Name = "Nathan Runolfsdottir"
                        },
                        new
                        {
                            StudentNumber = 115260,
                            Name = "Modesto Deckow"
                        },
                        new
                        {
                            StudentNumber = 115139,
                            Name = "Archibald Purdy"
                        },
                        new
                        {
                            StudentNumber = 115154,
                            Name = "Velva Hackett"
                        },
                        new
                        {
                            StudentNumber = 115501,
                            Name = "Leo Kling"
                        },
                        new
                        {
                            StudentNumber = 115201,
                            Name = "Mathew Fay"
                        },
                        new
                        {
                            StudentNumber = 115069,
                            Name = "Nikita Schuppe"
                        },
                        new
                        {
                            StudentNumber = 115344,
                            Name = "Kayley Schamberger"
                        },
                        new
                        {
                            StudentNumber = 115348,
                            Name = "Maximo King"
                        },
                        new
                        {
                            StudentNumber = 115300,
                            Name = "Jules Braun"
                        },
                        new
                        {
                            StudentNumber = 115433,
                            Name = "Sonny Leannon"
                        },
                        new
                        {
                            StudentNumber = 115194,
                            Name = "Evangeline Baumbach"
                        },
                        new
                        {
                            StudentNumber = 115312,
                            Name = "Kaleigh Leuschke"
                        },
                        new
                        {
                            StudentNumber = 115494,
                            Name = "Monica Rau"
                        },
                        new
                        {
                            StudentNumber = 115143,
                            Name = "Ashlee Lindgren"
                        },
                        new
                        {
                            StudentNumber = 115449,
                            Name = "Foster Schmeler"
                        },
                        new
                        {
                            StudentNumber = 115302,
                            Name = "Kenna Gorczany"
                        },
                        new
                        {
                            StudentNumber = 115081,
                            Name = "Cierra Schiller"
                        },
                        new
                        {
                            StudentNumber = 115444,
                            Name = "Margot Wisozk"
                        },
                        new
                        {
                            StudentNumber = 115229,
                            Name = "Helmer Spencer"
                        },
                        new
                        {
                            StudentNumber = 115471,
                            Name = "Lucius Johnson"
                        },
                        new
                        {
                            StudentNumber = 115468,
                            Name = "Kamille Orn"
                        },
                        new
                        {
                            StudentNumber = 115326,
                            Name = "Jess Kessler"
                        },
                        new
                        {
                            StudentNumber = 115464,
                            Name = "Geraldine Hackett"
                        },
                        new
                        {
                            StudentNumber = 115052,
                            Name = "Jaydon Blanda"
                        },
                        new
                        {
                            StudentNumber = 115292,
                            Name = "Porter Smith"
                        },
                        new
                        {
                            StudentNumber = 115503,
                            Name = "Gwen Moen"
                        },
                        new
                        {
                            StudentNumber = 115331,
                            Name = "Lexi Hermann"
                        },
                        new
                        {
                            StudentNumber = 115147,
                            Name = "Monica Goodwin"
                        },
                        new
                        {
                            StudentNumber = 115506,
                            Name = "Lazaro Murphy"
                        },
                        new
                        {
                            StudentNumber = 115382,
                            Name = "Adolph Nader"
                        },
                        new
                        {
                            StudentNumber = 115345,
                            Name = "Reed Anderson"
                        },
                        new
                        {
                            StudentNumber = 115079,
                            Name = "Jacinto Corwin"
                        },
                        new
                        {
                            StudentNumber = 115518,
                            Name = "Madisyn Fahey"
                        },
                        new
                        {
                            StudentNumber = 115527,
                            Name = "Isabel Morissette"
                        },
                        new
                        {
                            StudentNumber = 115459,
                            Name = "Cleve Mitchell"
                        },
                        new
                        {
                            StudentNumber = 115261,
                            Name = "Annamarie West"
                        },
                        new
                        {
                            StudentNumber = 115091,
                            Name = "Juwan Hintz"
                        },
                        new
                        {
                            StudentNumber = 115255,
                            Name = "Ethan Altenwerth"
                        },
                        new
                        {
                            StudentNumber = 115279,
                            Name = "Raven Spinka"
                        },
                        new
                        {
                            StudentNumber = 115200,
                            Name = "Columbus Legros"
                        },
                        new
                        {
                            StudentNumber = 115088,
                            Name = "Joshua Wisoky"
                        },
                        new
                        {
                            StudentNumber = 115366,
                            Name = "Freeda Lowe"
                        },
                        new
                        {
                            StudentNumber = 115055,
                            Name = "Emmie Fay"
                        },
                        new
                        {
                            StudentNumber = 115410,
                            Name = "Lenny Little"
                        },
                        new
                        {
                            StudentNumber = 115339,
                            Name = "Eric Dare"
                        },
                        new
                        {
                            StudentNumber = 115212,
                            Name = "Enrico Luettgen"
                        },
                        new
                        {
                            StudentNumber = 115288,
                            Name = "Oran Wiegand"
                        },
                        new
                        {
                            StudentNumber = 115103,
                            Name = "Albertha Monahan"
                        },
                        new
                        {
                            StudentNumber = 115233,
                            Name = "Sydnie Murazik"
                        },
                        new
                        {
                            StudentNumber = 115370,
                            Name = "Alaina Koepp"
                        });
                });

            modelBuilder.Entity("Model.GroupStudent", b =>
                {
                    b.HasOne("Model.Group", "Group")
                        .WithMany("GroupStudents")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Student", "Student")
                        .WithMany("GroupStudents")
                        .HasForeignKey("StudentNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Model.Group", b =>
                {
                    b.Navigation("GroupStudents");
                });

            modelBuilder.Entity("Model.Student", b =>
                {
                    b.Navigation("GroupStudents");
                });
#pragma warning restore 612, 618
        }
    }
}
