// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Service.Database;

#nullable disable

namespace Service.Database.Migrations
{
    [DbContext(typeof(AssessmentContext))]
    [Migration("90000000000000_DebugSeed")]
    partial class DebugSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Model.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupId"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("GroupId");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            GroupId = 1,
                            Name = "Champlin, Franecki and Leannon",
                            Number = 4
                        },
                        new
                        {
                            GroupId = 2,
                            Name = "Bogisich, Hahn and Metz",
                            Number = 1
                        },
                        new
                        {
                            GroupId = 3,
                            Name = "Howell Group",
                            Number = 5
                        },
                        new
                        {
                            GroupId = 4,
                            Name = "Breitenberg Inc and Sons",
                            Number = 2
                        },
                        new
                        {
                            GroupId = 5,
                            Name = "Herzog, Brekke and Bahringer",
                            Number = 5
                        },
                        new
                        {
                            GroupId = 6,
                            Name = "Auer-Pouros",
                            Number = 2
                        },
                        new
                        {
                            GroupId = 7,
                            Name = "Treutel LLC",
                            Number = 2
                        },
                        new
                        {
                            GroupId = 8,
                            Name = "Denesik, Wintheiser and Trantow",
                            Number = 1
                        },
                        new
                        {
                            GroupId = 9,
                            Name = "Cruickshank LLC",
                            Number = 6
                        },
                        new
                        {
                            GroupId = 10,
                            Name = "Schultz Inc and Sons",
                            Number = 2
                        },
                        new
                        {
                            GroupId = 11,
                            Name = "Stokes-Heller",
                            Number = 4
                        },
                        new
                        {
                            GroupId = 12,
                            Name = "Rosenbaum Group",
                            Number = 5
                        },
                        new
                        {
                            GroupId = 13,
                            Name = "Langosh Group",
                            Number = 6
                        },
                        new
                        {
                            GroupId = 14,
                            Name = "Hettinger Group",
                            Number = 4
                        },
                        new
                        {
                            GroupId = 15,
                            Name = "Wunsch-Bailey",
                            Number = 6
                        },
                        new
                        {
                            GroupId = 16,
                            Name = "Shanahan, Lakin and Klocko",
                            Number = 3
                        },
                        new
                        {
                            GroupId = 17,
                            Name = "Herzog-Sawayn",
                            Number = 5
                        },
                        new
                        {
                            GroupId = 18,
                            Name = "Jacobson, Hauck and Schimmel",
                            Number = 4
                        },
                        new
                        {
                            GroupId = 19,
                            Name = "Rodriguez Group",
                            Number = 4
                        },
                        new
                        {
                            GroupId = 20,
                            Name = "Muller-Konopelski",
                            Number = 4
                        },
                        new
                        {
                            GroupId = 21,
                            Name = "Schowalter-Barton",
                            Number = 2
                        },
                        new
                        {
                            GroupId = 22,
                            Name = "Swaniawski, Grant and Abernathy",
                            Number = 5
                        },
                        new
                        {
                            GroupId = 23,
                            Name = "Larson, Collier and Bergstrom",
                            Number = 5
                        },
                        new
                        {
                            GroupId = 24,
                            Name = "Wisoky, D'Amore and Lowe",
                            Number = 4
                        },
                        new
                        {
                            GroupId = 25,
                            Name = "Huels, Fay and Bayer",
                            Number = 5
                        },
                        new
                        {
                            GroupId = 26,
                            Name = "Deckow Group",
                            Number = 5
                        },
                        new
                        {
                            GroupId = 27,
                            Name = "Bernhard, Schultz and Stracke",
                            Number = 5
                        },
                        new
                        {
                            GroupId = 28,
                            Name = "Cormier Group",
                            Number = 4
                        },
                        new
                        {
                            GroupId = 29,
                            Name = "Rice, Gottlieb and Jaskolski",
                            Number = 1
                        },
                        new
                        {
                            GroupId = 30,
                            Name = "Kautzer Group",
                            Number = 6
                        },
                        new
                        {
                            GroupId = 31,
                            Name = "Bradtke, Schuppe and Mann",
                            Number = 2
                        },
                        new
                        {
                            GroupId = 32,
                            Name = "Keeling-Waters",
                            Number = 4
                        },
                        new
                        {
                            GroupId = 33,
                            Name = "McCullough-Yost",
                            Number = 4
                        },
                        new
                        {
                            GroupId = 34,
                            Name = "Zulauf-Feeney",
                            Number = 3
                        },
                        new
                        {
                            GroupId = 35,
                            Name = "Mohr, Cronin and Hagenes",
                            Number = 4
                        },
                        new
                        {
                            GroupId = 36,
                            Name = "Crooks Inc and Sons",
                            Number = 6
                        },
                        new
                        {
                            GroupId = 37,
                            Name = "Heaney, Schaefer and Grimes",
                            Number = 1
                        },
                        new
                        {
                            GroupId = 38,
                            Name = "Harvey-Breitenberg",
                            Number = 2
                        },
                        new
                        {
                            GroupId = 39,
                            Name = "Durgan, Mertz and Schmidt",
                            Number = 1
                        });
                });

            modelBuilder.Entity("Model.GroupStudent", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("StudentNumber")
                        .HasColumnType("int");

                    b.HasKey("GroupId", "StudentNumber");

                    b.HasIndex("StudentNumber");

                    b.ToTable("GroupStudent");

                    b.HasData(
                        new
                        {
                            GroupId = 1,
                            StudentNumber = 115058
                        },
                        new
                        {
                            GroupId = 1,
                            StudentNumber = 115341
                        },
                        new
                        {
                            GroupId = 1,
                            StudentNumber = 115554
                        },
                        new
                        {
                            GroupId = 1,
                            StudentNumber = 115457
                        },
                        new
                        {
                            GroupId = 1,
                            StudentNumber = 115483
                        },
                        new
                        {
                            GroupId = 1,
                            StudentNumber = 115846
                        },
                        new
                        {
                            GroupId = 1,
                            StudentNumber = 115401
                        },
                        new
                        {
                            GroupId = 1,
                            StudentNumber = 115425
                        },
                        new
                        {
                            GroupId = 2,
                            StudentNumber = 115444
                        },
                        new
                        {
                            GroupId = 2,
                            StudentNumber = 115899
                        },
                        new
                        {
                            GroupId = 2,
                            StudentNumber = 115307
                        },
                        new
                        {
                            GroupId = 3,
                            StudentNumber = 115609
                        },
                        new
                        {
                            GroupId = 3,
                            StudentNumber = 115670
                        },
                        new
                        {
                            GroupId = 3,
                            StudentNumber = 115269
                        },
                        new
                        {
                            GroupId = 3,
                            StudentNumber = 115873
                        },
                        new
                        {
                            GroupId = 3,
                            StudentNumber = 115903
                        },
                        new
                        {
                            GroupId = 3,
                            StudentNumber = 115769
                        },
                        new
                        {
                            GroupId = 3,
                            StudentNumber = 115023
                        },
                        new
                        {
                            GroupId = 3,
                            StudentNumber = 115711
                        },
                        new
                        {
                            GroupId = 4,
                            StudentNumber = 115194
                        },
                        new
                        {
                            GroupId = 4,
                            StudentNumber = 115413
                        },
                        new
                        {
                            GroupId = 4,
                            StudentNumber = 115873
                        },
                        new
                        {
                            GroupId = 4,
                            StudentNumber = 115248
                        },
                        new
                        {
                            GroupId = 5,
                            StudentNumber = 115264
                        },
                        new
                        {
                            GroupId = 5,
                            StudentNumber = 115095
                        },
                        new
                        {
                            GroupId = 5,
                            StudentNumber = 115770
                        },
                        new
                        {
                            GroupId = 6,
                            StudentNumber = 115317
                        },
                        new
                        {
                            GroupId = 6,
                            StudentNumber = 115425
                        },
                        new
                        {
                            GroupId = 6,
                            StudentNumber = 115401
                        },
                        new
                        {
                            GroupId = 6,
                            StudentNumber = 115482
                        },
                        new
                        {
                            GroupId = 7,
                            StudentNumber = 115315
                        },
                        new
                        {
                            GroupId = 7,
                            StudentNumber = 115001
                        },
                        new
                        {
                            GroupId = 7,
                            StudentNumber = 115482
                        },
                        new
                        {
                            GroupId = 7,
                            StudentNumber = 115272
                        },
                        new
                        {
                            GroupId = 7,
                            StudentNumber = 115246
                        },
                        new
                        {
                            GroupId = 7,
                            StudentNumber = 115154
                        },
                        new
                        {
                            GroupId = 7,
                            StudentNumber = 115027
                        },
                        new
                        {
                            GroupId = 7,
                            StudentNumber = 115096
                        },
                        new
                        {
                            GroupId = 8,
                            StudentNumber = 115614
                        },
                        new
                        {
                            GroupId = 8,
                            StudentNumber = 115864
                        },
                        new
                        {
                            GroupId = 8,
                            StudentNumber = 115058
                        },
                        new
                        {
                            GroupId = 8,
                            StudentNumber = 115036
                        },
                        new
                        {
                            GroupId = 8,
                            StudentNumber = 115566
                        },
                        new
                        {
                            GroupId = 8,
                            StudentNumber = 115500
                        },
                        new
                        {
                            GroupId = 8,
                            StudentNumber = 115349
                        },
                        new
                        {
                            GroupId = 9,
                            StudentNumber = 115264
                        },
                        new
                        {
                            GroupId = 9,
                            StudentNumber = 115306
                        },
                        new
                        {
                            GroupId = 9,
                            StudentNumber = 115765
                        },
                        new
                        {
                            GroupId = 9,
                            StudentNumber = 115138
                        },
                        new
                        {
                            GroupId = 9,
                            StudentNumber = 115211
                        },
                        new
                        {
                            GroupId = 10,
                            StudentNumber = 115141
                        },
                        new
                        {
                            GroupId = 10,
                            StudentNumber = 115089
                        },
                        new
                        {
                            GroupId = 10,
                            StudentNumber = 115305
                        },
                        new
                        {
                            GroupId = 10,
                            StudentNumber = 115401
                        },
                        new
                        {
                            GroupId = 10,
                            StudentNumber = 115770
                        },
                        new
                        {
                            GroupId = 10,
                            StudentNumber = 115293
                        },
                        new
                        {
                            GroupId = 11,
                            StudentNumber = 115889
                        },
                        new
                        {
                            GroupId = 11,
                            StudentNumber = 115007
                        },
                        new
                        {
                            GroupId = 11,
                            StudentNumber = 115058
                        },
                        new
                        {
                            GroupId = 11,
                            StudentNumber = 115108
                        },
                        new
                        {
                            GroupId = 11,
                            StudentNumber = 115079
                        },
                        new
                        {
                            GroupId = 12,
                            StudentNumber = 115494
                        },
                        new
                        {
                            GroupId = 12,
                            StudentNumber = 115220
                        },
                        new
                        {
                            GroupId = 12,
                            StudentNumber = 115573
                        },
                        new
                        {
                            GroupId = 12,
                            StudentNumber = 115508
                        },
                        new
                        {
                            GroupId = 12,
                            StudentNumber = 115166
                        },
                        new
                        {
                            GroupId = 12,
                            StudentNumber = 115221
                        },
                        new
                        {
                            GroupId = 12,
                            StudentNumber = 115466
                        },
                        new
                        {
                            GroupId = 12,
                            StudentNumber = 115554
                        },
                        new
                        {
                            GroupId = 13,
                            StudentNumber = 115855
                        },
                        new
                        {
                            GroupId = 13,
                            StudentNumber = 115336
                        },
                        new
                        {
                            GroupId = 14,
                            StudentNumber = 115414
                        },
                        new
                        {
                            GroupId = 14,
                            StudentNumber = 115486
                        },
                        new
                        {
                            GroupId = 14,
                            StudentNumber = 115306
                        },
                        new
                        {
                            GroupId = 14,
                            StudentNumber = 115731
                        },
                        new
                        {
                            GroupId = 15,
                            StudentNumber = 115169
                        },
                        new
                        {
                            GroupId = 15,
                            StudentNumber = 115542
                        },
                        new
                        {
                            GroupId = 15,
                            StudentNumber = 115007
                        },
                        new
                        {
                            GroupId = 15,
                            StudentNumber = 115261
                        },
                        new
                        {
                            GroupId = 16,
                            StudentNumber = 115896
                        },
                        new
                        {
                            GroupId = 16,
                            StudentNumber = 115125
                        },
                        new
                        {
                            GroupId = 16,
                            StudentNumber = 115810
                        },
                        new
                        {
                            GroupId = 16,
                            StudentNumber = 115235
                        },
                        new
                        {
                            GroupId = 17,
                            StudentNumber = 115058
                        },
                        new
                        {
                            GroupId = 17,
                            StudentNumber = 115846
                        },
                        new
                        {
                            GroupId = 17,
                            StudentNumber = 115045
                        },
                        new
                        {
                            GroupId = 17,
                            StudentNumber = 115185
                        },
                        new
                        {
                            GroupId = 17,
                            StudentNumber = 115454
                        },
                        new
                        {
                            GroupId = 18,
                            StudentNumber = 115154
                        },
                        new
                        {
                            GroupId = 18,
                            StudentNumber = 115598
                        },
                        new
                        {
                            GroupId = 18,
                            StudentNumber = 115816
                        },
                        new
                        {
                            GroupId = 18,
                            StudentNumber = 115494
                        },
                        new
                        {
                            GroupId = 18,
                            StudentNumber = 115253
                        },
                        new
                        {
                            GroupId = 18,
                            StudentNumber = 115012
                        },
                        new
                        {
                            GroupId = 19,
                            StudentNumber = 115185
                        },
                        new
                        {
                            GroupId = 19,
                            StudentNumber = 115475
                        },
                        new
                        {
                            GroupId = 19,
                            StudentNumber = 115619
                        },
                        new
                        {
                            GroupId = 19,
                            StudentNumber = 115286
                        },
                        new
                        {
                            GroupId = 19,
                            StudentNumber = 115269
                        },
                        new
                        {
                            GroupId = 19,
                            StudentNumber = 115741
                        },
                        new
                        {
                            GroupId = 19,
                            StudentNumber = 115004
                        },
                        new
                        {
                            GroupId = 19,
                            StudentNumber = 115879
                        },
                        new
                        {
                            GroupId = 20,
                            StudentNumber = 115264
                        },
                        new
                        {
                            GroupId = 20,
                            StudentNumber = 115482
                        },
                        new
                        {
                            GroupId = 20,
                            StudentNumber = 115899
                        },
                        new
                        {
                            GroupId = 20,
                            StudentNumber = 115770
                        },
                        new
                        {
                            GroupId = 20,
                            StudentNumber = 115154
                        },
                        new
                        {
                            GroupId = 21,
                            StudentNumber = 115264
                        },
                        new
                        {
                            GroupId = 21,
                            StudentNumber = 115736
                        },
                        new
                        {
                            GroupId = 21,
                            StudentNumber = 115211
                        },
                        new
                        {
                            GroupId = 21,
                            StudentNumber = 115883
                        },
                        new
                        {
                            GroupId = 22,
                            StudentNumber = 115614
                        },
                        new
                        {
                            GroupId = 22,
                            StudentNumber = 115121
                        },
                        new
                        {
                            GroupId = 22,
                            StudentNumber = 115500
                        },
                        new
                        {
                            GroupId = 22,
                            StudentNumber = 115588
                        },
                        new
                        {
                            GroupId = 22,
                            StudentNumber = 115279
                        },
                        new
                        {
                            GroupId = 22,
                            StudentNumber = 115674
                        },
                        new
                        {
                            GroupId = 22,
                            StudentNumber = 115141
                        },
                        new
                        {
                            GroupId = 22,
                            StudentNumber = 115365
                        },
                        new
                        {
                            GroupId = 23,
                            StudentNumber = 115619
                        },
                        new
                        {
                            GroupId = 23,
                            StudentNumber = 115007
                        },
                        new
                        {
                            GroupId = 23,
                            StudentNumber = 115422
                        },
                        new
                        {
                            GroupId = 23,
                            StudentNumber = 115540
                        },
                        new
                        {
                            GroupId = 23,
                            StudentNumber = 115113
                        },
                        new
                        {
                            GroupId = 23,
                            StudentNumber = 115840
                        },
                        new
                        {
                            GroupId = 24,
                            StudentNumber = 115143
                        },
                        new
                        {
                            GroupId = 24,
                            StudentNumber = 115540
                        },
                        new
                        {
                            GroupId = 24,
                            StudentNumber = 115588
                        },
                        new
                        {
                            GroupId = 25,
                            StudentNumber = 115789
                        },
                        new
                        {
                            GroupId = 25,
                            StudentNumber = 115248
                        },
                        new
                        {
                            GroupId = 26,
                            StudentNumber = 115430
                        },
                        new
                        {
                            GroupId = 26,
                            StudentNumber = 115879
                        },
                        new
                        {
                            GroupId = 26,
                            StudentNumber = 115650
                        },
                        new
                        {
                            GroupId = 26,
                            StudentNumber = 115357
                        },
                        new
                        {
                            GroupId = 26,
                            StudentNumber = 115095
                        },
                        new
                        {
                            GroupId = 26,
                            StudentNumber = 115154
                        },
                        new
                        {
                            GroupId = 27,
                            StudentNumber = 115444
                        },
                        new
                        {
                            GroupId = 27,
                            StudentNumber = 115344
                        },
                        new
                        {
                            GroupId = 27,
                            StudentNumber = 115585
                        },
                        new
                        {
                            GroupId = 27,
                            StudentNumber = 115215
                        },
                        new
                        {
                            GroupId = 27,
                            StudentNumber = 115154
                        },
                        new
                        {
                            GroupId = 28,
                            StudentNumber = 115864
                        },
                        new
                        {
                            GroupId = 28,
                            StudentNumber = 115840
                        },
                        new
                        {
                            GroupId = 28,
                            StudentNumber = 115004
                        },
                        new
                        {
                            GroupId = 28,
                            StudentNumber = 115212
                        },
                        new
                        {
                            GroupId = 29,
                            StudentNumber = 115036
                        },
                        new
                        {
                            GroupId = 29,
                            StudentNumber = 115483
                        },
                        new
                        {
                            GroupId = 29,
                            StudentNumber = 115315
                        },
                        new
                        {
                            GroupId = 29,
                            StudentNumber = 115113
                        },
                        new
                        {
                            GroupId = 29,
                            StudentNumber = 115096
                        },
                        new
                        {
                            GroupId = 29,
                            StudentNumber = 115889
                        },
                        new
                        {
                            GroupId = 30,
                            StudentNumber = 115769
                        },
                        new
                        {
                            GroupId = 30,
                            StudentNumber = 115483
                        },
                        new
                        {
                            GroupId = 30,
                            StudentNumber = 115125
                        },
                        new
                        {
                            GroupId = 30,
                            StudentNumber = 115359
                        },
                        new
                        {
                            GroupId = 30,
                            StudentNumber = 115663
                        },
                        new
                        {
                            GroupId = 30,
                            StudentNumber = 115709
                        },
                        new
                        {
                            GroupId = 30,
                            StudentNumber = 115269
                        },
                        new
                        {
                            GroupId = 31,
                            StudentNumber = 115792
                        },
                        new
                        {
                            GroupId = 31,
                            StudentNumber = 115566
                        },
                        new
                        {
                            GroupId = 31,
                            StudentNumber = 115882
                        },
                        new
                        {
                            GroupId = 31,
                            StudentNumber = 115194
                        },
                        new
                        {
                            GroupId = 31,
                            StudentNumber = 115563
                        },
                        new
                        {
                            GroupId = 31,
                            StudentNumber = 115270
                        },
                        new
                        {
                            GroupId = 32,
                            StudentNumber = 115009
                        },
                        new
                        {
                            GroupId = 32,
                            StudentNumber = 115095
                        },
                        new
                        {
                            GroupId = 32,
                            StudentNumber = 115220
                        },
                        new
                        {
                            GroupId = 32,
                            StudentNumber = 115785
                        },
                        new
                        {
                            GroupId = 32,
                            StudentNumber = 115773
                        },
                        new
                        {
                            GroupId = 32,
                            StudentNumber = 115906
                        },
                        new
                        {
                            GroupId = 33,
                            StudentNumber = 115225
                        },
                        new
                        {
                            GroupId = 33,
                            StudentNumber = 115307
                        },
                        new
                        {
                            GroupId = 33,
                            StudentNumber = 115834
                        },
                        new
                        {
                            GroupId = 33,
                            StudentNumber = 115256
                        },
                        new
                        {
                            GroupId = 33,
                            StudentNumber = 115887
                        },
                        new
                        {
                            GroupId = 33,
                            StudentNumber = 115799
                        },
                        new
                        {
                            GroupId = 33,
                            StudentNumber = 115253
                        },
                        new
                        {
                            GroupId = 34,
                            StudentNumber = 115687
                        },
                        new
                        {
                            GroupId = 34,
                            StudentNumber = 115903
                        },
                        new
                        {
                            GroupId = 34,
                            StudentNumber = 115165
                        },
                        new
                        {
                            GroupId = 34,
                            StudentNumber = 115711
                        },
                        new
                        {
                            GroupId = 35,
                            StudentNumber = 115619
                        },
                        new
                        {
                            GroupId = 35,
                            StudentNumber = 115045
                        },
                        new
                        {
                            GroupId = 35,
                            StudentNumber = 115269
                        },
                        new
                        {
                            GroupId = 35,
                            StudentNumber = 115864
                        },
                        new
                        {
                            GroupId = 35,
                            StudentNumber = 115256
                        },
                        new
                        {
                            GroupId = 36,
                            StudentNumber = 115425
                        },
                        new
                        {
                            GroupId = 36,
                            StudentNumber = 115234
                        },
                        new
                        {
                            GroupId = 37,
                            StudentNumber = 115269
                        },
                        new
                        {
                            GroupId = 37,
                            StudentNumber = 115883
                        },
                        new
                        {
                            GroupId = 37,
                            StudentNumber = 115359
                        },
                        new
                        {
                            GroupId = 37,
                            StudentNumber = 115354
                        },
                        new
                        {
                            GroupId = 37,
                            StudentNumber = 115542
                        },
                        new
                        {
                            GroupId = 38,
                            StudentNumber = 115816
                        },
                        new
                        {
                            GroupId = 38,
                            StudentNumber = 115703
                        },
                        new
                        {
                            GroupId = 38,
                            StudentNumber = 115001
                        },
                        new
                        {
                            GroupId = 38,
                            StudentNumber = 115108
                        },
                        new
                        {
                            GroupId = 39,
                            StudentNumber = 115422
                        },
                        new
                        {
                            GroupId = 39,
                            StudentNumber = 115266
                        },
                        new
                        {
                            GroupId = 39,
                            StudentNumber = 115874
                        },
                        new
                        {
                            GroupId = 39,
                            StudentNumber = 115896
                        },
                        new
                        {
                            GroupId = 39,
                            StudentNumber = 115466
                        });
                });

            modelBuilder.Entity("Model.Student", b =>
                {
                    b.Property<int>("StudentNumber")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentNumber");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentNumber = 115873,
                            Name = "Mrs. Marilie Grant Bechtelar"
                        },
                        new
                        {
                            StudentNumber = 115121,
                            Name = "Mrs. Gust Schmitt"
                        },
                        new
                        {
                            StudentNumber = 115456,
                            Name = "Barrett Rempel"
                        },
                        new
                        {
                            StudentNumber = 115372,
                            Name = "Minerva Williamson"
                        },
                        new
                        {
                            StudentNumber = 115302,
                            Name = "Daren Rau"
                        },
                        new
                        {
                            StudentNumber = 115781,
                            Name = "Chaz Gusikowski"
                        },
                        new
                        {
                            StudentNumber = 115793,
                            Name = "Dock Friesen"
                        },
                        new
                        {
                            StudentNumber = 115663,
                            Name = "Aubree Gusikowski"
                        },
                        new
                        {
                            StudentNumber = 115200,
                            Name = "Mr. Fausto Davis"
                        },
                        new
                        {
                            StudentNumber = 115253,
                            Name = "Kenya White"
                        },
                        new
                        {
                            StudentNumber = 115425,
                            Name = "Ms. Zachariah Hoeger"
                        },
                        new
                        {
                            StudentNumber = 115598,
                            Name = "Marquis Rohan"
                        },
                        new
                        {
                            StudentNumber = 115620,
                            Name = "Robin Friesen"
                        },
                        new
                        {
                            StudentNumber = 115269,
                            Name = "Graciela Bayer"
                        },
                        new
                        {
                            StudentNumber = 115899,
                            Name = "Miss Ocie Jakubowski IV"
                        },
                        new
                        {
                            StudentNumber = 115215,
                            Name = "Andres Stokes"
                        },
                        new
                        {
                            StudentNumber = 115760,
                            Name = "Laisha Bartell"
                        },
                        new
                        {
                            StudentNumber = 115154,
                            Name = "Edgardo Heathcote"
                        },
                        new
                        {
                            StudentNumber = 115306,
                            Name = "Dorothy Roberts"
                        },
                        new
                        {
                            StudentNumber = 115001,
                            Name = "Dejah Quitzon"
                        },
                        new
                        {
                            StudentNumber = 115879,
                            Name = "Gretchen Jamarcus Carroll II"
                        },
                        new
                        {
                            StudentNumber = 115170,
                            Name = "Floy Bartell"
                        },
                        new
                        {
                            StudentNumber = 115076,
                            Name = "Omer O'Hara"
                        },
                        new
                        {
                            StudentNumber = 115341,
                            Name = "Karina Cormier"
                        },
                        new
                        {
                            StudentNumber = 115089,
                            Name = "Vesta Von"
                        },
                        new
                        {
                            StudentNumber = 115344,
                            Name = "Margarett Metz"
                        },
                        new
                        {
                            StudentNumber = 115792,
                            Name = "Marisol Nitzsche"
                        },
                        new
                        {
                            StudentNumber = 115483,
                            Name = "Columbus Emard"
                        },
                        new
                        {
                            StudentNumber = 115096,
                            Name = "Mr. Veda Cartwright Sr."
                        },
                        new
                        {
                            StudentNumber = 115220,
                            Name = "Claudine Feil"
                        },
                        new
                        {
                            StudentNumber = 115711,
                            Name = "Dr. Brando Glenda Casper Jr."
                        },
                        new
                        {
                            StudentNumber = 115034,
                            Name = "Miss Dock Rocky Lubowitz Sr."
                        },
                        new
                        {
                            StudentNumber = 115357,
                            Name = "Gilberto Metz"
                        },
                        new
                        {
                            StudentNumber = 115079,
                            Name = "Nat Pattie Cruickshank I"
                        },
                        new
                        {
                            StudentNumber = 115043,
                            Name = "Demario Heidenreich"
                        },
                        new
                        {
                            StudentNumber = 115538,
                            Name = "Prof. Lynn Torrey Sawayn DDS"
                        },
                        new
                        {
                            StudentNumber = 115542,
                            Name = "Davon Connelly"
                        },
                        new
                        {
                            StudentNumber = 115846,
                            Name = "Noble Padberg"
                        },
                        new
                        {
                            StudentNumber = 115279,
                            Name = "Mrs. Ashlynn Herman"
                        },
                        new
                        {
                            StudentNumber = 115708,
                            Name = "Hank Nicolas"
                        },
                        new
                        {
                            StudentNumber = 115234,
                            Name = "Prof. Toby O'Keefe DDS"
                        },
                        new
                        {
                            StudentNumber = 115650,
                            Name = "Vilma Ziemann V"
                        },
                        new
                        {
                            StudentNumber = 115799,
                            Name = "Lou Morissette"
                        },
                        new
                        {
                            StudentNumber = 115125,
                            Name = "Marcelle Durgan"
                        },
                        new
                        {
                            StudentNumber = 115009,
                            Name = "Hudson Hilpert"
                        },
                        new
                        {
                            StudentNumber = 115588,
                            Name = "Mr. Frederic Taya Legros"
                        },
                        new
                        {
                            StudentNumber = 115397,
                            Name = "Mr. Arlo Funk"
                        },
                        new
                        {
                            StudentNumber = 115537,
                            Name = "Miss Noemie Hodkiewicz"
                        },
                        new
                        {
                            StudentNumber = 115887,
                            Name = "Fanny Ullrich"
                        },
                        new
                        {
                            StudentNumber = 115032,
                            Name = "Elmore Waters"
                        },
                        new
                        {
                            StudentNumber = 115264,
                            Name = "Dr. Devante O'Reilly"
                        },
                        new
                        {
                            StudentNumber = 115573,
                            Name = "Birdie McGlynn"
                        },
                        new
                        {
                            StudentNumber = 115045,
                            Name = "Jerrell Hodkiewicz I"
                        },
                        new
                        {
                            StudentNumber = 115823,
                            Name = "Rosalind Russel"
                        },
                        new
                        {
                            StudentNumber = 115204,
                            Name = "Dr. Filomena Prohaska DVM"
                        },
                        new
                        {
                            StudentNumber = 115609,
                            Name = "Evans Parker"
                        },
                        new
                        {
                            StudentNumber = 115563,
                            Name = "Loyal Streich"
                        },
                        new
                        {
                            StudentNumber = 115359,
                            Name = "Amara Marquardt"
                        },
                        new
                        {
                            StudentNumber = 115108,
                            Name = "Isai Champlin"
                        },
                        new
                        {
                            StudentNumber = 115631,
                            Name = "Aryanna Will"
                        },
                        new
                        {
                            StudentNumber = 115390,
                            Name = "Ms. Shanel Morar II"
                        },
                        new
                        {
                            StudentNumber = 115482,
                            Name = "Okey Kutch"
                        },
                        new
                        {
                            StudentNumber = 115457,
                            Name = "Gus Sauer"
                        },
                        new
                        {
                            StudentNumber = 115165,
                            Name = "Ms. Malachi Brenden Fadel Sr."
                        },
                        new
                        {
                            StudentNumber = 115414,
                            Name = "Prof. Megane Funk"
                        },
                        new
                        {
                            StudentNumber = 115324,
                            Name = "Mrs. Javon Witting"
                        },
                        new
                        {
                            StudentNumber = 115508,
                            Name = "Edwina Schoen"
                        },
                        new
                        {
                            StudentNumber = 115906,
                            Name = "Flo Genesis Collier PhD"
                        },
                        new
                        {
                            StudentNumber = 115256,
                            Name = "Ms. Brenna Roosevelt West II"
                        },
                        new
                        {
                            StudentNumber = 115430,
                            Name = "Rosemary Sanford"
                        },
                        new
                        {
                            StudentNumber = 115832,
                            Name = "Hester D'Amore"
                        },
                        new
                        {
                            StudentNumber = 115855,
                            Name = "Arturo Ziemann"
                        },
                        new
                        {
                            StudentNumber = 115765,
                            Name = "Dr. Justyn Sheldon Kuhic"
                        },
                        new
                        {
                            StudentNumber = 115769,
                            Name = "Fabian O'Kon"
                        },
                        new
                        {
                            StudentNumber = 115329,
                            Name = "Orion Hauck"
                        },
                        new
                        {
                            StudentNumber = 115444,
                            Name = "Lyric Bernier"
                        },
                        new
                        {
                            StudentNumber = 115007,
                            Name = "Bettye Jacobs"
                        },
                        new
                        {
                            StudentNumber = 115272,
                            Name = "Sean Schuster"
                        },
                        new
                        {
                            StudentNumber = 115441,
                            Name = "Mrs. Judge Bode"
                        },
                        new
                        {
                            StudentNumber = 115736,
                            Name = "Leone Mueller"
                        },
                        new
                        {
                            StudentNumber = 115293,
                            Name = "Mrs. Craig Boyle IV"
                        },
                        new
                        {
                            StudentNumber = 115903,
                            Name = "Alexanne Stamm"
                        },
                        new
                        {
                            StudentNumber = 115004,
                            Name = "Nigel Thiel"
                        },
                        new
                        {
                            StudentNumber = 115413,
                            Name = "Dejuan Klein"
                        },
                        new
                        {
                            StudentNumber = 115095,
                            Name = "Ms. Kattie Wilkinson"
                        },
                        new
                        {
                            StudentNumber = 115670,
                            Name = "Annamae Torphy"
                        },
                        new
                        {
                            StudentNumber = 115674,
                            Name = "Hyman Turcotte"
                        },
                        new
                        {
                            StudentNumber = 115810,
                            Name = "Elwyn Abshire"
                        },
                        new
                        {
                            StudentNumber = 115613,
                            Name = "Mr. Jayson Virgie Mitchell"
                        },
                        new
                        {
                            StudentNumber = 115612,
                            Name = "Pete Catherine Bruen V"
                        },
                        new
                        {
                            StudentNumber = 115023,
                            Name = "Ms. Jadyn Jamar Ratke"
                        },
                        new
                        {
                            StudentNumber = 115789,
                            Name = "Ms. Alan McClure"
                        },
                        new
                        {
                            StudentNumber = 115732,
                            Name = "Ray Block PhD"
                        },
                        new
                        {
                            StudentNumber = 115494,
                            Name = "Matt Weimann"
                        },
                        new
                        {
                            StudentNumber = 115315,
                            Name = "Miss Luna Nola Herzog III"
                        },
                        new
                        {
                            StudentNumber = 115703,
                            Name = "Mrs. Myriam Hal Schuster I"
                        },
                        new
                        {
                            StudentNumber = 115349,
                            Name = "Brain Braun"
                        },
                        new
                        {
                            StudentNumber = 115113,
                            Name = "Taya Leffler"
                        },
                        new
                        {
                            StudentNumber = 115261,
                            Name = "Mylene Ledner"
                        },
                        new
                        {
                            StudentNumber = 115143,
                            Name = "Sienna Ziemann"
                        },
                        new
                        {
                            StudentNumber = 115221,
                            Name = "Emilie Bode"
                        },
                        new
                        {
                            StudentNumber = 115619,
                            Name = "Lucious Ebert"
                        },
                        new
                        {
                            StudentNumber = 115896,
                            Name = "Titus Kuvalis"
                        },
                        new
                        {
                            StudentNumber = 115834,
                            Name = "Miss Laney Parker DDS"
                        },
                        new
                        {
                            StudentNumber = 115130,
                            Name = "Natalia Donnelly"
                        },
                        new
                        {
                            StudentNumber = 115669,
                            Name = "Baron Toy"
                        },
                        new
                        {
                            StudentNumber = 115475,
                            Name = "Miss Hiram Claudia Zboncak"
                        },
                        new
                        {
                            StudentNumber = 115554,
                            Name = "Jerald Larson"
                        },
                        new
                        {
                            StudentNumber = 115638,
                            Name = "Julie Kutch"
                        },
                        new
                        {
                            StudentNumber = 115737,
                            Name = "Amani Howell"
                        },
                        new
                        {
                            StudentNumber = 115286,
                            Name = "Prof. Earline Grant"
                        },
                        new
                        {
                            StudentNumber = 115305,
                            Name = "Jordi Padberg"
                        },
                        new
                        {
                            StudentNumber = 115782,
                            Name = "Dr. Michaela Swift DVM"
                        },
                        new
                        {
                            StudentNumber = 115864,
                            Name = "Faustino Bernier"
                        },
                        new
                        {
                            StudentNumber = 115763,
                            Name = "Frieda Huels"
                        },
                        new
                        {
                            StudentNumber = 115161,
                            Name = "Ms. Timmy Schneider"
                        },
                        new
                        {
                            StudentNumber = 115107,
                            Name = "Prof. Vallie Kenna Gutkowski II"
                        },
                        new
                        {
                            StudentNumber = 115317,
                            Name = "Zachary Bogisich"
                        },
                        new
                        {
                            StudentNumber = 115270,
                            Name = "Ms. Allan Llewellyn Krajcik I"
                        },
                        new
                        {
                            StudentNumber = 115194,
                            Name = "Korbin Roberts"
                        },
                        new
                        {
                            StudentNumber = 115129,
                            Name = "Andrew Schulist PhD"
                        },
                        new
                        {
                            StudentNumber = 115874,
                            Name = "Prof. Leslie Jessie Carroll PhD"
                        },
                        new
                        {
                            StudentNumber = 115036,
                            Name = "Myles Ryleigh Christiansen PhD"
                        },
                        new
                        {
                            StudentNumber = 115566,
                            Name = "Annamarie Howe"
                        },
                        new
                        {
                            StudentNumber = 115368,
                            Name = "Daija Bahringer"
                        },
                        new
                        {
                            StudentNumber = 115773,
                            Name = "Melany Cartwright MD"
                        },
                        new
                        {
                            StudentNumber = 115144,
                            Name = "Constantin Aisha Kerluke Jr."
                        },
                        new
                        {
                            StudentNumber = 115211,
                            Name = "Isabel Metz"
                        },
                        new
                        {
                            StudentNumber = 115235,
                            Name = "Lauryn Altenwerth"
                        },
                        new
                        {
                            StudentNumber = 115786,
                            Name = "Dane Smitham"
                        },
                        new
                        {
                            StudentNumber = 115540,
                            Name = "Berry Schultz"
                        },
                        new
                        {
                            StudentNumber = 115047,
                            Name = "Korbin Maggio"
                        },
                        new
                        {
                            StudentNumber = 115587,
                            Name = "Prof. Kamron Graham V"
                        },
                        new
                        {
                            StudentNumber = 115437,
                            Name = "Marlene Rippin"
                        },
                        new
                        {
                            StudentNumber = 115500,
                            Name = "Ms. Mattie Aidan Turner II"
                        },
                        new
                        {
                            StudentNumber = 115889,
                            Name = "Mariano Sheridan Corwin III"
                        },
                        new
                        {
                            StudentNumber = 115454,
                            Name = "Prof. Alison Littel"
                        },
                        new
                        {
                            StudentNumber = 115882,
                            Name = "Mr. Tyrique Margot Raynor"
                        },
                        new
                        {
                            StudentNumber = 115307,
                            Name = "Ms. Kennith Justina Casper"
                        },
                        new
                        {
                            StudentNumber = 115180,
                            Name = "Emiliano Mosciski"
                        },
                        new
                        {
                            StudentNumber = 115883,
                            Name = "Millie Ferry"
                        },
                        new
                        {
                            StudentNumber = 115248,
                            Name = "Karli Ratke"
                        },
                        new
                        {
                            StudentNumber = 115770,
                            Name = "Mr. Tanya Morar"
                        },
                        new
                        {
                            StudentNumber = 115027,
                            Name = "Johan Heidenreich Sr."
                        },
                        new
                        {
                            StudentNumber = 115909,
                            Name = "Anthony Bartell"
                        },
                        new
                        {
                            StudentNumber = 115466,
                            Name = "Madonna Murray"
                        },
                        new
                        {
                            StudentNumber = 115058,
                            Name = "Glen Harris"
                        },
                        new
                        {
                            StudentNumber = 115785,
                            Name = "Narciso Greenfelder"
                        },
                        new
                        {
                            StudentNumber = 115012,
                            Name = "Billie Hahn"
                        },
                        new
                        {
                            StudentNumber = 115378,
                            Name = "Mrs. Gerry Orin Hamill"
                        },
                        new
                        {
                            StudentNumber = 115365,
                            Name = "Cydney Tillman"
                        },
                        new
                        {
                            StudentNumber = 115422,
                            Name = "Prof. Gerda Josue Durgan Jr."
                        },
                        new
                        {
                            StudentNumber = 115141,
                            Name = "Dr. Dianna Ziemann"
                        },
                        new
                        {
                            StudentNumber = 115401,
                            Name = "Vernie Parker"
                        },
                        new
                        {
                            StudentNumber = 115246,
                            Name = "Dayne Metz"
                        },
                        new
                        {
                            StudentNumber = 115816,
                            Name = "Sanford Fritsch"
                        },
                        new
                        {
                            StudentNumber = 115138,
                            Name = "Vaughn Stracke"
                        },
                        new
                        {
                            StudentNumber = 115169,
                            Name = "Prof. Karianne Mason Harber"
                        },
                        new
                        {
                            StudentNumber = 115266,
                            Name = "Mr. Mazie Dibbert"
                        },
                        new
                        {
                            StudentNumber = 115212,
                            Name = "Prof. Allene Timothy McClure DDS"
                        },
                        new
                        {
                            StudentNumber = 115336,
                            Name = "Alfonzo Dayana O'Conner V"
                        },
                        new
                        {
                            StudentNumber = 115687,
                            Name = "Jordyn Spencer"
                        },
                        new
                        {
                            StudentNumber = 115644,
                            Name = "Damon Smith"
                        },
                        new
                        {
                            StudentNumber = 115486,
                            Name = "Gabe Schaefer"
                        },
                        new
                        {
                            StudentNumber = 115498,
                            Name = "Velda Hortense Murazik IV"
                        },
                        new
                        {
                            StudentNumber = 115334,
                            Name = "Harry Langworth DVM"
                        },
                        new
                        {
                            StudentNumber = 115216,
                            Name = "Loyce Casper V"
                        },
                        new
                        {
                            StudentNumber = 115233,
                            Name = "Joanny Lindgren Sr."
                        },
                        new
                        {
                            StudentNumber = 115868,
                            Name = "Mrs. Kristian Hailie Haley"
                        },
                        new
                        {
                            StudentNumber = 115354,
                            Name = "Alysha Rowe"
                        },
                        new
                        {
                            StudentNumber = 115731,
                            Name = "Ms. Mark Hyatt"
                        },
                        new
                        {
                            StudentNumber = 115285,
                            Name = "Ms. Cathrine Garett Walter DVM"
                        },
                        new
                        {
                            StudentNumber = 115166,
                            Name = "Emily Jakubowski Jr."
                        },
                        new
                        {
                            StudentNumber = 115185,
                            Name = "Savannah Anderson"
                        },
                        new
                        {
                            StudentNumber = 115255,
                            Name = "Isobel Pollich"
                        },
                        new
                        {
                            StudentNumber = 115709,
                            Name = "Mr. Colton Connelly DDS"
                        },
                        new
                        {
                            StudentNumber = 115585,
                            Name = "Mrs. Rosemary Osborne Rogahn"
                        },
                        new
                        {
                            StudentNumber = 115599,
                            Name = "Mrs. Bella Lauren Wiza IV"
                        },
                        new
                        {
                            StudentNumber = 115614,
                            Name = "Marcelle Rice"
                        },
                        new
                        {
                            StudentNumber = 115225,
                            Name = "Delia Cummerata"
                        },
                        new
                        {
                            StudentNumber = 115741,
                            Name = "Junior Aylin Wintheiser I"
                        },
                        new
                        {
                            StudentNumber = 115840,
                            Name = "Orpha Hoppe"
                        });
                });

            modelBuilder.Entity("Model.GroupStudent", b =>
                {
                    b.HasOne("Model.Group", "Group")
                        .WithMany("GroupStudents")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Student", "Student")
                        .WithMany("GroupStudents")
                        .HasForeignKey("StudentNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Model.Group", b =>
                {
                    b.Navigation("GroupStudents");
                });

            modelBuilder.Entity("Model.Student", b =>
                {
                    b.Navigation("GroupStudents");
                });
#pragma warning restore 612, 618
        }
    }
}
