// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Service.Database;

#nullable disable

namespace Service.Database.Migrations
{
    [DbContext(typeof(AssessmentContext))]
    [Migration("90000000000000_DebugSeed")]
    partial class DebugSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Model.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupId"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("GroupId");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            GroupId = 1,
                            Name = "Labadie, Rolfson and Hahn",
                            Number = 2
                        },
                        new
                        {
                            GroupId = 2,
                            Name = "Hayes LLC",
                            Number = 6
                        },
                        new
                        {
                            GroupId = 3,
                            Name = "Ruecker-Mosciski",
                            Number = 2
                        },
                        new
                        {
                            GroupId = 4,
                            Name = "Wilderman Inc and Sons",
                            Number = 5
                        },
                        new
                        {
                            GroupId = 5,
                            Name = "DuBuque, Veum and Koepp",
                            Number = 4
                        },
                        new
                        {
                            GroupId = 6,
                            Name = "Russel, Hoeger and Steuber",
                            Number = 3
                        },
                        new
                        {
                            GroupId = 7,
                            Name = "Graham, Goldner and Casper",
                            Number = 3
                        },
                        new
                        {
                            GroupId = 8,
                            Name = "Shanahan-Fritsch",
                            Number = 5
                        },
                        new
                        {
                            GroupId = 9,
                            Name = "Heaney, Champlin and Keeling",
                            Number = 5
                        },
                        new
                        {
                            GroupId = 10,
                            Name = "Abbott-Jewess",
                            Number = 2
                        },
                        new
                        {
                            GroupId = 11,
                            Name = "Mueller, Morissette and Kris",
                            Number = 5
                        },
                        new
                        {
                            GroupId = 12,
                            Name = "Bernier LLC",
                            Number = 6
                        },
                        new
                        {
                            GroupId = 13,
                            Name = "Stamm-Runolfsson",
                            Number = 4
                        },
                        new
                        {
                            GroupId = 14,
                            Name = "Sipes Group",
                            Number = 3
                        },
                        new
                        {
                            GroupId = 15,
                            Name = "O'Hara, VonRueden and Dare",
                            Number = 3
                        },
                        new
                        {
                            GroupId = 16,
                            Name = "Trantow, Rosenbaum and Kohler",
                            Number = 6
                        },
                        new
                        {
                            GroupId = 17,
                            Name = "Hansen, Bernhard and Hammes",
                            Number = 3
                        },
                        new
                        {
                            GroupId = 18,
                            Name = "Hagenes-Bashirian",
                            Number = 6
                        },
                        new
                        {
                            GroupId = 19,
                            Name = "Conroy Inc and Sons",
                            Number = 3
                        },
                        new
                        {
                            GroupId = 20,
                            Name = "Dicki-Mitchell",
                            Number = 2
                        },
                        new
                        {
                            GroupId = 21,
                            Name = "Gottlieb-Osinski",
                            Number = 1
                        },
                        new
                        {
                            GroupId = 22,
                            Name = "Heaney LLC",
                            Number = 2
                        },
                        new
                        {
                            GroupId = 23,
                            Name = "Feest, Howell and Swift",
                            Number = 5
                        },
                        new
                        {
                            GroupId = 24,
                            Name = "Conroy, Hand and Jewess",
                            Number = 5
                        },
                        new
                        {
                            GroupId = 25,
                            Name = "Anderson-Goyette",
                            Number = 6
                        });
                });

            modelBuilder.Entity("Model.GroupStudent", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("StudentNumber")
                        .HasColumnType("int");

                    b.HasKey("GroupId", "StudentNumber");

                    b.HasIndex("StudentNumber");

                    b.ToTable("GroupStudent");

                    b.HasData(
                        new
                        {
                            GroupId = 1,
                            StudentNumber = 115056
                        },
                        new
                        {
                            GroupId = 1,
                            StudentNumber = 115052
                        },
                        new
                        {
                            GroupId = 1,
                            StudentNumber = 115134
                        },
                        new
                        {
                            GroupId = 1,
                            StudentNumber = 115157
                        },
                        new
                        {
                            GroupId = 1,
                            StudentNumber = 115145
                        },
                        new
                        {
                            GroupId = 1,
                            StudentNumber = 115118
                        },
                        new
                        {
                            GroupId = 1,
                            StudentNumber = 115339
                        },
                        new
                        {
                            GroupId = 1,
                            StudentNumber = 115350
                        },
                        new
                        {
                            GroupId = 2,
                            StudentNumber = 115047
                        },
                        new
                        {
                            GroupId = 2,
                            StudentNumber = 115088
                        },
                        new
                        {
                            GroupId = 2,
                            StudentNumber = 115367
                        },
                        new
                        {
                            GroupId = 2,
                            StudentNumber = 115103
                        },
                        new
                        {
                            GroupId = 2,
                            StudentNumber = 115125
                        },
                        new
                        {
                            GroupId = 2,
                            StudentNumber = 115118
                        },
                        new
                        {
                            GroupId = 2,
                            StudentNumber = 115020
                        },
                        new
                        {
                            GroupId = 2,
                            StudentNumber = 115292
                        },
                        new
                        {
                            GroupId = 3,
                            StudentNumber = 115385
                        },
                        new
                        {
                            GroupId = 3,
                            StudentNumber = 115303
                        },
                        new
                        {
                            GroupId = 3,
                            StudentNumber = 115007
                        },
                        new
                        {
                            GroupId = 3,
                            StudentNumber = 115140
                        },
                        new
                        {
                            GroupId = 3,
                            StudentNumber = 115367
                        },
                        new
                        {
                            GroupId = 3,
                            StudentNumber = 115283
                        },
                        new
                        {
                            GroupId = 4,
                            StudentNumber = 115200
                        },
                        new
                        {
                            GroupId = 4,
                            StudentNumber = 115218
                        },
                        new
                        {
                            GroupId = 4,
                            StudentNumber = 115409
                        },
                        new
                        {
                            GroupId = 4,
                            StudentNumber = 115039
                        },
                        new
                        {
                            GroupId = 4,
                            StudentNumber = 115418
                        },
                        new
                        {
                            GroupId = 4,
                            StudentNumber = 115047
                        },
                        new
                        {
                            GroupId = 4,
                            StudentNumber = 115292
                        },
                        new
                        {
                            GroupId = 5,
                            StudentNumber = 115288
                        },
                        new
                        {
                            GroupId = 5,
                            StudentNumber = 115438
                        },
                        new
                        {
                            GroupId = 6,
                            StudentNumber = 115368
                        },
                        new
                        {
                            GroupId = 6,
                            StudentNumber = 115059
                        },
                        new
                        {
                            GroupId = 6,
                            StudentNumber = 115303
                        },
                        new
                        {
                            GroupId = 6,
                            StudentNumber = 115385
                        },
                        new
                        {
                            GroupId = 6,
                            StudentNumber = 115089
                        },
                        new
                        {
                            GroupId = 6,
                            StudentNumber = 115023
                        },
                        new
                        {
                            GroupId = 7,
                            StudentNumber = 115056
                        },
                        new
                        {
                            GroupId = 7,
                            StudentNumber = 115372
                        },
                        new
                        {
                            GroupId = 7,
                            StudentNumber = 115230
                        },
                        new
                        {
                            GroupId = 7,
                            StudentNumber = 115045
                        },
                        new
                        {
                            GroupId = 7,
                            StudentNumber = 115104
                        },
                        new
                        {
                            GroupId = 8,
                            StudentNumber = 115088
                        },
                        new
                        {
                            GroupId = 8,
                            StudentNumber = 115163
                        },
                        new
                        {
                            GroupId = 8,
                            StudentNumber = 115218
                        },
                        new
                        {
                            GroupId = 8,
                            StudentNumber = 115303
                        },
                        new
                        {
                            GroupId = 8,
                            StudentNumber = 115076
                        },
                        new
                        {
                            GroupId = 8,
                            StudentNumber = 115342
                        },
                        new
                        {
                            GroupId = 8,
                            StudentNumber = 115007
                        },
                        new
                        {
                            GroupId = 9,
                            StudentNumber = 115292
                        },
                        new
                        {
                            GroupId = 9,
                            StudentNumber = 115134
                        },
                        new
                        {
                            GroupId = 9,
                            StudentNumber = 115231
                        },
                        new
                        {
                            GroupId = 9,
                            StudentNumber = 115128
                        },
                        new
                        {
                            GroupId = 9,
                            StudentNumber = 115118
                        },
                        new
                        {
                            GroupId = 9,
                            StudentNumber = 115172
                        },
                        new
                        {
                            GroupId = 9,
                            StudentNumber = 115353
                        },
                        new
                        {
                            GroupId = 9,
                            StudentNumber = 115256
                        },
                        new
                        {
                            GroupId = 10,
                            StudentNumber = 115385
                        },
                        new
                        {
                            GroupId = 10,
                            StudentNumber = 115409
                        },
                        new
                        {
                            GroupId = 10,
                            StudentNumber = 115046
                        },
                        new
                        {
                            GroupId = 10,
                            StudentNumber = 115380
                        },
                        new
                        {
                            GroupId = 10,
                            StudentNumber = 115167
                        },
                        new
                        {
                            GroupId = 10,
                            StudentNumber = 115091
                        },
                        new
                        {
                            GroupId = 11,
                            StudentNumber = 115018
                        },
                        new
                        {
                            GroupId = 11,
                            StudentNumber = 115012
                        },
                        new
                        {
                            GroupId = 11,
                            StudentNumber = 115283
                        },
                        new
                        {
                            GroupId = 11,
                            StudentNumber = 115145
                        },
                        new
                        {
                            GroupId = 11,
                            StudentNumber = 115302
                        },
                        new
                        {
                            GroupId = 12,
                            StudentNumber = 115218
                        },
                        new
                        {
                            GroupId = 12,
                            StudentNumber = 115350
                        },
                        new
                        {
                            GroupId = 12,
                            StudentNumber = 115018
                        },
                        new
                        {
                            GroupId = 12,
                            StudentNumber = 115353
                        },
                        new
                        {
                            GroupId = 12,
                            StudentNumber = 115314
                        },
                        new
                        {
                            GroupId = 13,
                            StudentNumber = 115071
                        },
                        new
                        {
                            GroupId = 13,
                            StudentNumber = 115350
                        },
                        new
                        {
                            GroupId = 13,
                            StudentNumber = 115329
                        },
                        new
                        {
                            GroupId = 13,
                            StudentNumber = 115240
                        },
                        new
                        {
                            GroupId = 13,
                            StudentNumber = 115397
                        },
                        new
                        {
                            GroupId = 14,
                            StudentNumber = 115101
                        },
                        new
                        {
                            GroupId = 14,
                            StudentNumber = 115395
                        },
                        new
                        {
                            GroupId = 15,
                            StudentNumber = 115299
                        },
                        new
                        {
                            GroupId = 15,
                            StudentNumber = 115057
                        },
                        new
                        {
                            GroupId = 15,
                            StudentNumber = 115012
                        },
                        new
                        {
                            GroupId = 15,
                            StudentNumber = 115418
                        },
                        new
                        {
                            GroupId = 16,
                            StudentNumber = 115385
                        },
                        new
                        {
                            GroupId = 16,
                            StudentNumber = 115125
                        },
                        new
                        {
                            GroupId = 17,
                            StudentNumber = 115385
                        },
                        new
                        {
                            GroupId = 17,
                            StudentNumber = 115248
                        },
                        new
                        {
                            GroupId = 17,
                            StudentNumber = 115051
                        },
                        new
                        {
                            GroupId = 17,
                            StudentNumber = 115435
                        },
                        new
                        {
                            GroupId = 17,
                            StudentNumber = 115227
                        },
                        new
                        {
                            GroupId = 18,
                            StudentNumber = 115134
                        },
                        new
                        {
                            GroupId = 18,
                            StudentNumber = 115329
                        },
                        new
                        {
                            GroupId = 18,
                            StudentNumber = 115283
                        },
                        new
                        {
                            GroupId = 18,
                            StudentNumber = 115376
                        },
                        new
                        {
                            GroupId = 18,
                            StudentNumber = 115174
                        },
                        new
                        {
                            GroupId = 18,
                            StudentNumber = 115414
                        },
                        new
                        {
                            GroupId = 18,
                            StudentNumber = 115200
                        },
                        new
                        {
                            GroupId = 18,
                            StudentNumber = 115288
                        },
                        new
                        {
                            GroupId = 19,
                            StudentNumber = 115059
                        },
                        new
                        {
                            GroupId = 19,
                            StudentNumber = 115174
                        },
                        new
                        {
                            GroupId = 19,
                            StudentNumber = 115039
                        },
                        new
                        {
                            GroupId = 19,
                            StudentNumber = 115227
                        },
                        new
                        {
                            GroupId = 19,
                            StudentNumber = 115252
                        },
                        new
                        {
                            GroupId = 19,
                            StudentNumber = 115302
                        },
                        new
                        {
                            GroupId = 19,
                            StudentNumber = 115292
                        },
                        new
                        {
                            GroupId = 19,
                            StudentNumber = 115329
                        },
                        new
                        {
                            GroupId = 20,
                            StudentNumber = 115134
                        },
                        new
                        {
                            GroupId = 20,
                            StudentNumber = 115376
                        },
                        new
                        {
                            GroupId = 20,
                            StudentNumber = 115409
                        },
                        new
                        {
                            GroupId = 20,
                            StudentNumber = 115007
                        },
                        new
                        {
                            GroupId = 21,
                            StudentNumber = 115395
                        },
                        new
                        {
                            GroupId = 21,
                            StudentNumber = 115056
                        },
                        new
                        {
                            GroupId = 21,
                            StudentNumber = 115218
                        },
                        new
                        {
                            GroupId = 21,
                            StudentNumber = 115144
                        },
                        new
                        {
                            GroupId = 22,
                            StudentNumber = 115292
                        },
                        new
                        {
                            GroupId = 22,
                            StudentNumber = 115248
                        },
                        new
                        {
                            GroupId = 22,
                            StudentNumber = 115102
                        },
                        new
                        {
                            GroupId = 22,
                            StudentNumber = 115174
                        },
                        new
                        {
                            GroupId = 22,
                            StudentNumber = 115076
                        },
                        new
                        {
                            GroupId = 23,
                            StudentNumber = 115418
                        },
                        new
                        {
                            GroupId = 23,
                            StudentNumber = 115176
                        },
                        new
                        {
                            GroupId = 24,
                            StudentNumber = 115337
                        },
                        new
                        {
                            GroupId = 24,
                            StudentNumber = 115302
                        },
                        new
                        {
                            GroupId = 24,
                            StudentNumber = 115283
                        },
                        new
                        {
                            GroupId = 24,
                            StudentNumber = 115157
                        },
                        new
                        {
                            GroupId = 24,
                            StudentNumber = 115103
                        },
                        new
                        {
                            GroupId = 24,
                            StudentNumber = 115007
                        },
                        new
                        {
                            GroupId = 24,
                            StudentNumber = 115039
                        },
                        new
                        {
                            GroupId = 24,
                            StudentNumber = 115303
                        },
                        new
                        {
                            GroupId = 25,
                            StudentNumber = 115181
                        },
                        new
                        {
                            GroupId = 25,
                            StudentNumber = 115367
                        },
                        new
                        {
                            GroupId = 25,
                            StudentNumber = 115018
                        },
                        new
                        {
                            GroupId = 25,
                            StudentNumber = 115368
                        },
                        new
                        {
                            GroupId = 25,
                            StudentNumber = 115265
                        },
                        new
                        {
                            GroupId = 25,
                            StudentNumber = 115051
                        },
                        new
                        {
                            GroupId = 25,
                            StudentNumber = 115023
                        });
                });

            modelBuilder.Entity("Model.Student", b =>
                {
                    b.Property<int>("StudentNumber")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentNumber");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentNumber = 115145,
                            Name = "Ms. Jacques Milan Lakin II"
                        },
                        new
                        {
                            StudentNumber = 115397,
                            Name = "Prof. Kaycee Marks"
                        },
                        new
                        {
                            StudentNumber = 115104,
                            Name = "Ms. Jaquelin Wilkinson"
                        },
                        new
                        {
                            StudentNumber = 115059,
                            Name = "Ms. Clarissa Rowe MD"
                        },
                        new
                        {
                            StudentNumber = 115385,
                            Name = "Prof. Icie Bernita Connelly"
                        },
                        new
                        {
                            StudentNumber = 115337,
                            Name = "Miss Isidro Gonzalo Pfannerstill"
                        },
                        new
                        {
                            StudentNumber = 115240,
                            Name = "Serena West"
                        },
                        new
                        {
                            StudentNumber = 115023,
                            Name = "Prof. Dell Gianni Herman V"
                        },
                        new
                        {
                            StudentNumber = 115299,
                            Name = "Hilario Kreiger"
                        },
                        new
                        {
                            StudentNumber = 115176,
                            Name = "Doyle Block"
                        },
                        new
                        {
                            StudentNumber = 115057,
                            Name = "Prof. Wilhelm Mariana Legros PhD"
                        },
                        new
                        {
                            StudentNumber = 115020,
                            Name = "Dr. Eliane Lance Cassin I"
                        },
                        new
                        {
                            StudentNumber = 115158,
                            Name = "Dixie Schoen"
                        },
                        new
                        {
                            StudentNumber = 115367,
                            Name = "Selena Tate Wehner DDS"
                        },
                        new
                        {
                            StudentNumber = 115088,
                            Name = "Ms. Louvenia Simonis"
                        },
                        new
                        {
                            StudentNumber = 115442,
                            Name = "Antonette Schroeder"
                        },
                        new
                        {
                            StudentNumber = 115418,
                            Name = "Ally Sanford"
                        },
                        new
                        {
                            StudentNumber = 115092,
                            Name = "Cierra Crist"
                        },
                        new
                        {
                            StudentNumber = 115346,
                            Name = "Chanelle Lindgren"
                        },
                        new
                        {
                            StudentNumber = 115272,
                            Name = "Kara Marianne Dickinson III"
                        },
                        new
                        {
                            StudentNumber = 115118,
                            Name = "Dr. Clay Samir Schuppe"
                        },
                        new
                        {
                            StudentNumber = 115438,
                            Name = "Matilde Christiansen"
                        },
                        new
                        {
                            StudentNumber = 115167,
                            Name = "Spencer Cummerata"
                        },
                        new
                        {
                            StudentNumber = 115056,
                            Name = "Alva Elmo Gleason II"
                        },
                        new
                        {
                            StudentNumber = 115125,
                            Name = "Ms. Mariana Alf Walker II"
                        },
                        new
                        {
                            StudentNumber = 115248,
                            Name = "Mrs. Scotty Edna Runte"
                        },
                        new
                        {
                            StudentNumber = 115414,
                            Name = "Ms. Audra Ward DVM"
                        },
                        new
                        {
                            StudentNumber = 115174,
                            Name = "Koby Walter"
                        },
                        new
                        {
                            StudentNumber = 115294,
                            Name = "Miss Jaida Kian Mante V"
                        },
                        new
                        {
                            StudentNumber = 115231,
                            Name = "Mrs. Gwendolyn Windler"
                        },
                        new
                        {
                            StudentNumber = 115039,
                            Name = "Anya Parker"
                        },
                        new
                        {
                            StudentNumber = 115102,
                            Name = "Ms. Queen Alyce Crooks"
                        },
                        new
                        {
                            StudentNumber = 115065,
                            Name = "Hobart Quigley"
                        },
                        new
                        {
                            StudentNumber = 115123,
                            Name = "Fiona Kassulke"
                        },
                        new
                        {
                            StudentNumber = 115261,
                            Name = "Darien Gibson"
                        },
                        new
                        {
                            StudentNumber = 115314,
                            Name = "Ronaldo Halvorson"
                        },
                        new
                        {
                            StudentNumber = 115292,
                            Name = "Thaddeus Tia Hand PhD"
                        },
                        new
                        {
                            StudentNumber = 115089,
                            Name = "Mr. Roslyn Beatty DVM"
                        },
                        new
                        {
                            StudentNumber = 115106,
                            Name = "Kiarra Rath"
                        },
                        new
                        {
                            StudentNumber = 115309,
                            Name = "Devan Kaitlyn Kiehn MD"
                        },
                        new
                        {
                            StudentNumber = 115051,
                            Name = "Gus Marks"
                        },
                        new
                        {
                            StudentNumber = 115448,
                            Name = "Dr. Ludie Efrain Wunsch PhD"
                        },
                        new
                        {
                            StudentNumber = 115435,
                            Name = "Timmy Parisian"
                        },
                        new
                        {
                            StudentNumber = 115018,
                            Name = "Mr. Kattie Blanche Emmerich"
                        },
                        new
                        {
                            StudentNumber = 115308,
                            Name = "Dominic Nolan"
                        },
                        new
                        {
                            StudentNumber = 115372,
                            Name = "Hope Kessler"
                        },
                        new
                        {
                            StudentNumber = 115342,
                            Name = "Muhammad Sporer"
                        },
                        new
                        {
                            StudentNumber = 115101,
                            Name = "Kevin Dwight Quigley DVM"
                        },
                        new
                        {
                            StudentNumber = 115128,
                            Name = "Mrs. Alex McKenzie I"
                        },
                        new
                        {
                            StudentNumber = 115052,
                            Name = "Astrid Daniel"
                        },
                        new
                        {
                            StudentNumber = 115103,
                            Name = "Etha Hermiston"
                        },
                        new
                        {
                            StudentNumber = 115265,
                            Name = "Alessandro Frami"
                        },
                        new
                        {
                            StudentNumber = 115302,
                            Name = "Ambrose Murazik III"
                        },
                        new
                        {
                            StudentNumber = 115047,
                            Name = "Donna Adolfo Larson Jr."
                        },
                        new
                        {
                            StudentNumber = 115076,
                            Name = "Katelin Maggio"
                        },
                        new
                        {
                            StudentNumber = 115353,
                            Name = "Rey Kuphal"
                        },
                        new
                        {
                            StudentNumber = 115283,
                            Name = "Prof. Elton Kameron D'Amore DDS"
                        },
                        new
                        {
                            StudentNumber = 115007,
                            Name = "Arch Blick III"
                        },
                        new
                        {
                            StudentNumber = 115345,
                            Name = "Myrtie Ritchie"
                        },
                        new
                        {
                            StudentNumber = 115329,
                            Name = "Mrs. Bernard Jimmy Wintheiser MD"
                        },
                        new
                        {
                            StudentNumber = 115140,
                            Name = "Emilie Berge"
                        },
                        new
                        {
                            StudentNumber = 115350,
                            Name = "Louvenia Cole"
                        },
                        new
                        {
                            StudentNumber = 115230,
                            Name = "Rubye Heaney"
                        },
                        new
                        {
                            StudentNumber = 115288,
                            Name = "Mrs. Kaya Cortney Blick V"
                        },
                        new
                        {
                            StudentNumber = 115339,
                            Name = "Teagan Jace Grimes PhD"
                        },
                        new
                        {
                            StudentNumber = 115409,
                            Name = "Jazmyne Upton"
                        },
                        new
                        {
                            StudentNumber = 115163,
                            Name = "Alanis Olson"
                        },
                        new
                        {
                            StudentNumber = 115095,
                            Name = "Wilfredo Magnus Reynolds II"
                        },
                        new
                        {
                            StudentNumber = 115218,
                            Name = "Mrs. Eve Sonya Becker DDS"
                        },
                        new
                        {
                            StudentNumber = 115227,
                            Name = "Russ Armstrong"
                        },
                        new
                        {
                            StudentNumber = 115144,
                            Name = "Shawna Rowe"
                        },
                        new
                        {
                            StudentNumber = 115019,
                            Name = "Ms. Elsa Aaron Stamm"
                        },
                        new
                        {
                            StudentNumber = 115200,
                            Name = "Alexane Miller DVM"
                        },
                        new
                        {
                            StudentNumber = 115071,
                            Name = "Elwin Bauch"
                        },
                        new
                        {
                            StudentNumber = 115172,
                            Name = "Noemie Konopelski"
                        },
                        new
                        {
                            StudentNumber = 115181,
                            Name = "Brenda Wunsch"
                        },
                        new
                        {
                            StudentNumber = 115395,
                            Name = "Prof. Onie Natasha Corkery Jr."
                        },
                        new
                        {
                            StudentNumber = 115444,
                            Name = "Jaqueline Rodriguez"
                        },
                        new
                        {
                            StudentNumber = 115134,
                            Name = "Cyrus Hilpert"
                        },
                        new
                        {
                            StudentNumber = 115256,
                            Name = "Domingo Little"
                        },
                        new
                        {
                            StudentNumber = 115157,
                            Name = "Ms. Guadalupe Pauline Hansen"
                        },
                        new
                        {
                            StudentNumber = 115368,
                            Name = "Terrance Kessler"
                        },
                        new
                        {
                            StudentNumber = 115012,
                            Name = "Brionna McLaughlin"
                        },
                        new
                        {
                            StudentNumber = 115045,
                            Name = "Deonte Fritsch DDS"
                        },
                        new
                        {
                            StudentNumber = 115380,
                            Name = "Dina Schimmel"
                        },
                        new
                        {
                            StudentNumber = 115252,
                            Name = "Miss Vickie Paucek"
                        },
                        new
                        {
                            StudentNumber = 115091,
                            Name = "Ms. Lambert Ryan"
                        },
                        new
                        {
                            StudentNumber = 115303,
                            Name = "Pierre Bruen"
                        },
                        new
                        {
                            StudentNumber = 115087,
                            Name = "Dominic Hoeger"
                        },
                        new
                        {
                            StudentNumber = 115376,
                            Name = "Elvis Weimann"
                        },
                        new
                        {
                            StudentNumber = 115046,
                            Name = "Ursula Margarita Koelpin IV"
                        });
                });

            modelBuilder.Entity("Model.GroupStudent", b =>
                {
                    b.HasOne("Model.Group", "Group")
                        .WithMany("GroupStudents")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Student", "Student")
                        .WithMany("GroupStudents")
                        .HasForeignKey("StudentNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Model.Group", b =>
                {
                    b.Navigation("GroupStudents");
                });

            modelBuilder.Entity("Model.Student", b =>
                {
                    b.Navigation("GroupStudents");
                });
#pragma warning restore 612, 618
        }
    }
}
