// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Service.Database;

#nullable disable

namespace Service.Database.Migrations
{
    [DbContext(typeof(AssessmentContext))]
    [Migration("20220519074623_Seed")]
    partial class Seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Model.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupId"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("GroupId");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            GroupId = 1,
                            Name = "Durgan LLC",
                            Number = 6
                        },
                        new
                        {
                            GroupId = 2,
                            Name = "Sauer, Hegmann and Quigley",
                            Number = 4
                        },
                        new
                        {
                            GroupId = 3,
                            Name = "Mann, Ullrich and Haley",
                            Number = 5
                        },
                        new
                        {
                            GroupId = 4,
                            Name = "Fadel-Bailey",
                            Number = 5
                        },
                        new
                        {
                            GroupId = 5,
                            Name = "Renner-Lind",
                            Number = 5
                        },
                        new
                        {
                            GroupId = 6,
                            Name = "Ward Group",
                            Number = 4
                        },
                        new
                        {
                            GroupId = 7,
                            Name = "Bailey Group",
                            Number = 1
                        },
                        new
                        {
                            GroupId = 8,
                            Name = "McDermott-Sanford",
                            Number = 1
                        },
                        new
                        {
                            GroupId = 9,
                            Name = "Torp, Waters and Keeling",
                            Number = 6
                        },
                        new
                        {
                            GroupId = 10,
                            Name = "Skiles-Gibson",
                            Number = 3
                        },
                        new
                        {
                            GroupId = 11,
                            Name = "Kihn-Cartwright",
                            Number = 2
                        },
                        new
                        {
                            GroupId = 12,
                            Name = "Ryan LLC",
                            Number = 4
                        },
                        new
                        {
                            GroupId = 13,
                            Name = "Welch-Goldner",
                            Number = 5
                        },
                        new
                        {
                            GroupId = 14,
                            Name = "Dare LLC",
                            Number = 2
                        },
                        new
                        {
                            GroupId = 15,
                            Name = "Schinner Inc and Sons",
                            Number = 5
                        },
                        new
                        {
                            GroupId = 16,
                            Name = "Harris LLC",
                            Number = 1
                        },
                        new
                        {
                            GroupId = 17,
                            Name = "Quigley Group",
                            Number = 1
                        },
                        new
                        {
                            GroupId = 18,
                            Name = "Price, Wuckert and Metz",
                            Number = 3
                        },
                        new
                        {
                            GroupId = 19,
                            Name = "Durgan Inc and Sons",
                            Number = 4
                        },
                        new
                        {
                            GroupId = 20,
                            Name = "O'Hara, Von and Ferry",
                            Number = 2
                        },
                        new
                        {
                            GroupId = 21,
                            Name = "Quigley-Friesen",
                            Number = 5
                        });
                });

            modelBuilder.Entity("Model.GroupStudent", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("StudentNumber")
                        .HasColumnType("int");

                    b.HasKey("GroupId", "StudentNumber");

                    b.HasIndex("StudentNumber");

                    b.ToTable("GroupStudent");

                    b.HasData(
                        new
                        {
                            GroupId = 1,
                            StudentNumber = 115124
                        },
                        new
                        {
                            GroupId = 1,
                            StudentNumber = 115044
                        },
                        new
                        {
                            GroupId = 1,
                            StudentNumber = 115298
                        },
                        new
                        {
                            GroupId = 1,
                            StudentNumber = 115127
                        },
                        new
                        {
                            GroupId = 1,
                            StudentNumber = 115213
                        },
                        new
                        {
                            GroupId = 1,
                            StudentNumber = 115196
                        },
                        new
                        {
                            GroupId = 1,
                            StudentNumber = 115018
                        },
                        new
                        {
                            GroupId = 2,
                            StudentNumber = 115309
                        },
                        new
                        {
                            GroupId = 2,
                            StudentNumber = 115153
                        },
                        new
                        {
                            GroupId = 3,
                            StudentNumber = 115165
                        },
                        new
                        {
                            GroupId = 3,
                            StudentNumber = 115018
                        },
                        new
                        {
                            GroupId = 4,
                            StudentNumber = 115013
                        },
                        new
                        {
                            GroupId = 4,
                            StudentNumber = 115235
                        },
                        new
                        {
                            GroupId = 4,
                            StudentNumber = 115064
                        },
                        new
                        {
                            GroupId = 5,
                            StudentNumber = 115384
                        },
                        new
                        {
                            GroupId = 5,
                            StudentNumber = 115201
                        },
                        new
                        {
                            GroupId = 5,
                            StudentNumber = 115005
                        },
                        new
                        {
                            GroupId = 5,
                            StudentNumber = 115213
                        },
                        new
                        {
                            GroupId = 6,
                            StudentNumber = 115214
                        },
                        new
                        {
                            GroupId = 6,
                            StudentNumber = 115133
                        },
                        new
                        {
                            GroupId = 7,
                            StudentNumber = 115352
                        },
                        new
                        {
                            GroupId = 7,
                            StudentNumber = 115386
                        },
                        new
                        {
                            GroupId = 7,
                            StudentNumber = 115091
                        },
                        new
                        {
                            GroupId = 7,
                            StudentNumber = 115221
                        },
                        new
                        {
                            GroupId = 7,
                            StudentNumber = 115299
                        },
                        new
                        {
                            GroupId = 7,
                            StudentNumber = 115073
                        },
                        new
                        {
                            GroupId = 7,
                            StudentNumber = 115318
                        },
                        new
                        {
                            GroupId = 8,
                            StudentNumber = 115172
                        },
                        new
                        {
                            GroupId = 8,
                            StudentNumber = 115044
                        },
                        new
                        {
                            GroupId = 9,
                            StudentNumber = 115298
                        },
                        new
                        {
                            GroupId = 9,
                            StudentNumber = 115304
                        },
                        new
                        {
                            GroupId = 9,
                            StudentNumber = 115352
                        },
                        new
                        {
                            GroupId = 10,
                            StudentNumber = 115378
                        },
                        new
                        {
                            GroupId = 10,
                            StudentNumber = 115218
                        },
                        new
                        {
                            GroupId = 11,
                            StudentNumber = 115375
                        },
                        new
                        {
                            GroupId = 11,
                            StudentNumber = 115264
                        },
                        new
                        {
                            GroupId = 11,
                            StudentNumber = 115194
                        },
                        new
                        {
                            GroupId = 12,
                            StudentNumber = 115181
                        },
                        new
                        {
                            GroupId = 12,
                            StudentNumber = 115228
                        },
                        new
                        {
                            GroupId = 12,
                            StudentNumber = 115125
                        },
                        new
                        {
                            GroupId = 12,
                            StudentNumber = 115136
                        },
                        new
                        {
                            GroupId = 12,
                            StudentNumber = 115059
                        },
                        new
                        {
                            GroupId = 12,
                            StudentNumber = 115128
                        },
                        new
                        {
                            GroupId = 13,
                            StudentNumber = 115127
                        },
                        new
                        {
                            GroupId = 13,
                            StudentNumber = 115059
                        },
                        new
                        {
                            GroupId = 13,
                            StudentNumber = 115138
                        },
                        new
                        {
                            GroupId = 13,
                            StudentNumber = 115198
                        },
                        new
                        {
                            GroupId = 13,
                            StudentNumber = 115176
                        },
                        new
                        {
                            GroupId = 13,
                            StudentNumber = 115257
                        },
                        new
                        {
                            GroupId = 13,
                            StudentNumber = 115194
                        },
                        new
                        {
                            GroupId = 13,
                            StudentNumber = 115221
                        },
                        new
                        {
                            GroupId = 14,
                            StudentNumber = 115165
                        },
                        new
                        {
                            GroupId = 14,
                            StudentNumber = 115056
                        },
                        new
                        {
                            GroupId = 14,
                            StudentNumber = 115342
                        },
                        new
                        {
                            GroupId = 14,
                            StudentNumber = 115064
                        },
                        new
                        {
                            GroupId = 14,
                            StudentNumber = 115091
                        },
                        new
                        {
                            GroupId = 15,
                            StudentNumber = 115386
                        },
                        new
                        {
                            GroupId = 15,
                            StudentNumber = 115252
                        },
                        new
                        {
                            GroupId = 16,
                            StudentNumber = 115350
                        },
                        new
                        {
                            GroupId = 16,
                            StudentNumber = 115073
                        },
                        new
                        {
                            GroupId = 16,
                            StudentNumber = 115025
                        },
                        new
                        {
                            GroupId = 16,
                            StudentNumber = 115046
                        },
                        new
                        {
                            GroupId = 17,
                            StudentNumber = 115194
                        },
                        new
                        {
                            GroupId = 17,
                            StudentNumber = 115299
                        },
                        new
                        {
                            GroupId = 17,
                            StudentNumber = 115214
                        },
                        new
                        {
                            GroupId = 17,
                            StudentNumber = 115139
                        },
                        new
                        {
                            GroupId = 18,
                            StudentNumber = 115299
                        },
                        new
                        {
                            GroupId = 18,
                            StudentNumber = 115288
                        },
                        new
                        {
                            GroupId = 18,
                            StudentNumber = 115181
                        },
                        new
                        {
                            GroupId = 18,
                            StudentNumber = 115342
                        },
                        new
                        {
                            GroupId = 18,
                            StudentNumber = 115147
                        },
                        new
                        {
                            GroupId = 18,
                            StudentNumber = 115013
                        },
                        new
                        {
                            GroupId = 19,
                            StudentNumber = 115018
                        },
                        new
                        {
                            GroupId = 19,
                            StudentNumber = 115046
                        },
                        new
                        {
                            GroupId = 20,
                            StudentNumber = 115127
                        },
                        new
                        {
                            GroupId = 20,
                            StudentNumber = 115384
                        },
                        new
                        {
                            GroupId = 20,
                            StudentNumber = 115261
                        },
                        new
                        {
                            GroupId = 20,
                            StudentNumber = 115131
                        },
                        new
                        {
                            GroupId = 21,
                            StudentNumber = 115114
                        },
                        new
                        {
                            GroupId = 21,
                            StudentNumber = 115131
                        });
                });

            modelBuilder.Entity("Model.Student", b =>
                {
                    b.Property<int>("StudentNumber")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentNumber");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentNumber = 115342,
                            Name = "Dax Von"
                        },
                        new
                        {
                            StudentNumber = 115091,
                            Name = "Mr. Savanah Florida Predovic"
                        },
                        new
                        {
                            StudentNumber = 115124,
                            Name = "Ms. Brook Johns"
                        },
                        new
                        {
                            StudentNumber = 115213,
                            Name = "Darron Gislason"
                        },
                        new
                        {
                            StudentNumber = 115201,
                            Name = "Jonathan Mosciski"
                        },
                        new
                        {
                            StudentNumber = 115282,
                            Name = "Sammie DuBuque"
                        },
                        new
                        {
                            StudentNumber = 115252,
                            Name = "Jennyfer Langosh"
                        },
                        new
                        {
                            StudentNumber = 115138,
                            Name = "Antwan Rey Carroll III"
                        },
                        new
                        {
                            StudentNumber = 115352,
                            Name = "Linnea Upton"
                        },
                        new
                        {
                            StudentNumber = 115288,
                            Name = "Kendrick Alden Kulas III"
                        },
                        new
                        {
                            StudentNumber = 115147,
                            Name = "Prof. Sierra Hyatt"
                        },
                        new
                        {
                            StudentNumber = 115127,
                            Name = "Susanna Walker"
                        },
                        new
                        {
                            StudentNumber = 115139,
                            Name = "Mrs. Esmeralda Kathleen Huels II"
                        },
                        new
                        {
                            StudentNumber = 115087,
                            Name = "Prof. Anya Jordon Kihn"
                        },
                        new
                        {
                            StudentNumber = 115060,
                            Name = "Raina Quitzon"
                        },
                        new
                        {
                            StudentNumber = 115309,
                            Name = "Woodrow Torphy Jr."
                        },
                        new
                        {
                            StudentNumber = 115025,
                            Name = "Mr. Madonna Philip Osinski"
                        },
                        new
                        {
                            StudentNumber = 115136,
                            Name = "Oleta Cruickshank"
                        },
                        new
                        {
                            StudentNumber = 115218,
                            Name = "Trystan Marvin"
                        },
                        new
                        {
                            StudentNumber = 115216,
                            Name = "Dr. Melisa Conrad Lemke"
                        },
                        new
                        {
                            StudentNumber = 115299,
                            Name = "Hans Doyle DVM"
                        },
                        new
                        {
                            StudentNumber = 115066,
                            Name = "Prof. Fredy Conor Block IV"
                        },
                        new
                        {
                            StudentNumber = 115261,
                            Name = "Miss Gilbert Finn Little"
                        },
                        new
                        {
                            StudentNumber = 115181,
                            Name = "Lottie Norma Reinger IV"
                        },
                        new
                        {
                            StudentNumber = 115114,
                            Name = "Jayda Stroman"
                        },
                        new
                        {
                            StudentNumber = 115046,
                            Name = "Bret Lavina Wolff Jr."
                        },
                        new
                        {
                            StudentNumber = 115257,
                            Name = "Ms. Gunner Alexanne Gorczany Jr."
                        },
                        new
                        {
                            StudentNumber = 115196,
                            Name = "Mrs. Mikel Halvorson DVM"
                        },
                        new
                        {
                            StudentNumber = 115390,
                            Name = "Clinton Aufderhar"
                        },
                        new
                        {
                            StudentNumber = 115235,
                            Name = "Elton Tyler Prosacco III"
                        },
                        new
                        {
                            StudentNumber = 115131,
                            Name = "Jayson Hoppe"
                        },
                        new
                        {
                            StudentNumber = 115370,
                            Name = "Ervin Hyatt DVM"
                        },
                        new
                        {
                            StudentNumber = 115194,
                            Name = "Deven Bergnaum"
                        },
                        new
                        {
                            StudentNumber = 115160,
                            Name = "Miss Kobe Tyson Homenick MD"
                        },
                        new
                        {
                            StudentNumber = 115106,
                            Name = "Megane Schuster"
                        },
                        new
                        {
                            StudentNumber = 115281,
                            Name = "Lowell Hodkiewicz"
                        },
                        new
                        {
                            StudentNumber = 115079,
                            Name = "Brennon Kilback V"
                        },
                        new
                        {
                            StudentNumber = 115073,
                            Name = "Bria Gutkowski"
                        },
                        new
                        {
                            StudentNumber = 115225,
                            Name = "Dr. Kristin Kemmer"
                        },
                        new
                        {
                            StudentNumber = 115298,
                            Name = "Kenny Trinity Mraz I"
                        },
                        new
                        {
                            StudentNumber = 115365,
                            Name = "Stephania Hintz"
                        },
                        new
                        {
                            StudentNumber = 115195,
                            Name = "Prof. Lucie Giles Daniel"
                        },
                        new
                        {
                            StudentNumber = 115379,
                            Name = "Jaydon Welch"
                        },
                        new
                        {
                            StudentNumber = 115212,
                            Name = "Hertha Mosciski"
                        },
                        new
                        {
                            StudentNumber = 115378,
                            Name = "Mona Volkman"
                        },
                        new
                        {
                            StudentNumber = 115033,
                            Name = "Ms. Izaiah Eichmann"
                        },
                        new
                        {
                            StudentNumber = 115259,
                            Name = "Savion Kiehn"
                        },
                        new
                        {
                            StudentNumber = 115214,
                            Name = "Guadalupe Turner"
                        },
                        new
                        {
                            StudentNumber = 115373,
                            Name = "Asha Koss Jr."
                        },
                        new
                        {
                            StudentNumber = 115125,
                            Name = "Karley Marks"
                        },
                        new
                        {
                            StudentNumber = 115133,
                            Name = "Nolan Schamberger"
                        },
                        new
                        {
                            StudentNumber = 115314,
                            Name = "Sasha Willms"
                        },
                        new
                        {
                            StudentNumber = 115350,
                            Name = "Bessie Prudence Bartell Jr."
                        },
                        new
                        {
                            StudentNumber = 115176,
                            Name = "Cullen Weissnat"
                        },
                        new
                        {
                            StudentNumber = 115002,
                            Name = "Mrs. Marlene Jerde Jr."
                        },
                        new
                        {
                            StudentNumber = 115172,
                            Name = "Sedrick Matteo Beier DVM"
                        },
                        new
                        {
                            StudentNumber = 115076,
                            Name = "Ardith Johns"
                        },
                        new
                        {
                            StudentNumber = 115059,
                            Name = "Dr. Candice Ward II"
                        },
                        new
                        {
                            StudentNumber = 115375,
                            Name = "Mrs. Oda Franco Morissette MD"
                        },
                        new
                        {
                            StudentNumber = 115408,
                            Name = "Brannon Sporer"
                        },
                        new
                        {
                            StudentNumber = 115056,
                            Name = "Jayce Schoen"
                        },
                        new
                        {
                            StudentNumber = 115032,
                            Name = "Gertrude Pollich"
                        },
                        new
                        {
                            StudentNumber = 115115,
                            Name = "Moses Pagac"
                        },
                        new
                        {
                            StudentNumber = 115198,
                            Name = "Mrs. Tressa Ambrose Crist"
                        },
                        new
                        {
                            StudentNumber = 115318,
                            Name = "Gerry Heaney IV"
                        },
                        new
                        {
                            StudentNumber = 115128,
                            Name = "Danika Crona"
                        },
                        new
                        {
                            StudentNumber = 115013,
                            Name = "Creola Ralph Kreiger DDS"
                        },
                        new
                        {
                            StudentNumber = 115005,
                            Name = "Bruce Feil"
                        },
                        new
                        {
                            StudentNumber = 115386,
                            Name = "Ms. Brisa Carole Frami III"
                        },
                        new
                        {
                            StudentNumber = 115055,
                            Name = "Prof. Precious Mohr Jr."
                        },
                        new
                        {
                            StudentNumber = 115018,
                            Name = "Dr. Hassie Shields"
                        },
                        new
                        {
                            StudentNumber = 115264,
                            Name = "Shaniya Treutel"
                        },
                        new
                        {
                            StudentNumber = 115165,
                            Name = "Shayna Gerlach MD"
                        },
                        new
                        {
                            StudentNumber = 115044,
                            Name = "Taylor McKenzie"
                        },
                        new
                        {
                            StudentNumber = 115221,
                            Name = "Eleazar Hermann"
                        },
                        new
                        {
                            StudentNumber = 115000,
                            Name = "Ella Barrows"
                        },
                        new
                        {
                            StudentNumber = 115328,
                            Name = "Carmelo Hodkiewicz"
                        },
                        new
                        {
                            StudentNumber = 115064,
                            Name = "Sammie Breitenberg"
                        },
                        new
                        {
                            StudentNumber = 115384,
                            Name = "Jade Breitenberg"
                        },
                        new
                        {
                            StudentNumber = 115228,
                            Name = "Russ Prohaska"
                        },
                        new
                        {
                            StudentNumber = 115153,
                            Name = "Efrain Mills"
                        },
                        new
                        {
                            StudentNumber = 115304,
                            Name = "Reanna Hermann MD"
                        });
                });

            modelBuilder.Entity("Model.GroupStudent", b =>
                {
                    b.HasOne("Model.Group", "Group")
                        .WithMany("GroupStudents")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Student", "Student")
                        .WithMany("GroupStudents")
                        .HasForeignKey("StudentNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Model.Group", b =>
                {
                    b.Navigation("GroupStudents");
                });

            modelBuilder.Entity("Model.Student", b =>
                {
                    b.Navigation("GroupStudents");
                });
#pragma warning restore 612, 618
        }
    }
}
